// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file AutoFormat basic/auto-format.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'auto-format',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M3 6C3 5.44772 3.32335 5 3.72222 5H15.2778C15.6767 5 16 5.44772 16 6C16 6.55228 15.6767 7 15.2778 7H3.72222C3.32335 7 3 6.55228 3 6Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M3 12C3 11.4477 3.3444 11 3.76923 11H12.2308C12.6556 11 13 11.4477 13 12C13 12.5523 12.6556 13 12.2308 13H3.76923C3.3444 13 3 12.5523 3 12Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2.97488 17.9749C2.97488 17.4226 3.4226 16.9749 3.97488 16.9749H19.9749C20.5272 16.9749 20.9749 17.4226 20.9749 17.9749C20.9749 18.5272 20.5272 18.9749 19.9749 18.9749H3.97488C3.4226 18.9749 2.97488 18.5272 2.97488 17.9749Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
