// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file BookmarkView basic/bookmark-view.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'bookmark-view',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M4 9.6875C4 9.19382 4.33133 9 4.5 9H8L8 16H4.5C4.33133 16 4 15.8062 4 15.3125V9.6875ZM10 16H19.5C19.6687 16 20 15.8062 20 15.3125V9.6875C20 9.19382 19.6687 9 19.5 9H10L10 16ZM4.5 7C3.01181 7 2 8.31722 2 9.6875V15.3125C2 16.6828 3.01181 18 4.5 18H19.5C20.9882 18 22 16.6828 22 15.3125V9.6875C22 8.31722 20.9882 7 19.5 7H4.5Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
