// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Browser basic/browser.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'browser',
    false,
    (props: ISvgIconProps) => (
        <svg
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                strokeLinejoin="round"
                strokeLinecap="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="M21 9v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9"
            />
            <path
                strokeLinejoin="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="M3 4a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v5H3V4z"
            />
            <path
                fill={props.colors[0]}
                d="M6 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"
                clipRule="evenodd"
                fillRule="evenodd"
            />
        </svg>
    )
);
