// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file CheckboxCircle checkbox/checkbox-circle.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'checkbox-circle',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M12 19C15.866 19 19 15.866 19 12C19 8.13401 15.866 5 12 5C8.13401 5 5 8.13401 5 12C5 15.866 8.13401 19 12 19ZM12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M17.3211 8.05752C17.8416 8.511 17.896 9.30059 17.4425 9.82111L12.2152 15.8211C11.9938 16.0752 11.6793 16.2291 11.3428 16.248C11.0063 16.2669 10.6765 16.1492 10.4281 15.9214L7.15534 12.9214C6.64645 12.455 6.61207 11.6642 7.07856 11.1553C7.54505 10.6464 8.33576 10.6121 8.84466 11.0786L11.1724 13.2123L15.5575 8.1789C16.011 7.65837 16.8006 7.60403 17.3211 8.05752Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
