// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file FontSize rich-text/font-size.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'font-size',
    false,
    (props: ISvgIconProps) => (
        <svg
            viewBox="0 0 24 24"
            width={props.size}
            height={props.size}
            fill="none"
        >
            <path
                fill={props.colors[0]}
                d="M3 3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v2.467a1 1 0 1 1-2 0V4h-6v16h3a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h3V4H5v1.467a1 1 0 0 1-2 0V3z"
                clipRule="evenodd"
                fillRule="evenodd"
            />
        </svg>
    )
);
