// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Link basic/link.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'link',
    false,
    (props: ISvgIconProps) => (
        <svg
            viewBox="0 0 24 24"
            height={props.size}
            width={props.size}
            fill="none"
        >
            <path
                fill={props.colors[0]}
                d="M10.456 8.178c1.424 0 2.789.565 3.795 1.571a1 1 0 0 1-1.414 1.415 3.368 3.368 0 0 0-4.6-.152l-.162.152-3.089 3.087a3.368 3.368 0 0 0 4.6 4.915l.163-.152 1.544-1.544a1 1 0 0 1 1.498 1.32l-.084.094-1.544 1.544A5.368 5.368 0 0 1 3.39 13.03l.183-.193 3.09-3.088a5.368 5.368 0 0 1 3.794-1.571zM16.633 2a5.368 5.368 0 0 1 3.979 8.97l-.184.194-3.089 3.088a5.368 5.368 0 0 1-7.59 0 1 1 0 1 1 1.414-1.415 3.368 3.368 0 0 0 4.6.152l.162-.152 3.09-3.088a3.368 3.368 0 0 0-4.601-4.915l-.163.152-1.544 1.544a1 1 0 0 1-1.497-1.32l.083-.094 1.544-1.544A5.368 5.368 0 0 1 16.633 2z"
            />
        </svg>
    )
);
