// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Minus basic/minus.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'minus',
    false,
    (props: ISvgIconProps) => (
        <svg
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                strokeLinejoin="round"
                strokeLinecap="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="M5.25 12h14"
            />
        </svg>
    )
);
