// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Range rich-text/range.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'range',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M17.2929 8.29289C17.6834 7.90237 18.3166 7.90237 18.7071 8.29289L21.7071 11.2929C22.0976 11.6834 22.0976 12.3166 21.7071 12.7071L18.7071 15.7071C18.3166 16.0976 17.6834 16.0976 17.2929 15.7071C16.9024 15.3166 16.9024 14.6834 17.2929 14.2929L19.5858 12L17.2929 9.70711C16.9024 9.31658 16.9024 8.68342 17.2929 8.29289Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M6.70711 15.7071C6.31658 16.0976 5.68342 16.0976 5.29289 15.7071L2.29289 12.7071C1.90237 12.3166 1.90237 11.6834 2.29289 11.2929L5.29289 8.29289C5.68342 7.90237 6.31658 7.90237 6.70711 8.29289C7.09763 8.68342 7.09763 9.31658 6.70711 9.70711L4.41421 12L6.70711 14.2929C7.09763 14.6834 7.09763 15.3166 6.70711 15.7071Z"
                fill={props.colors[0]}
            />
            <circle
                cx="8"
                cy="12"
                r="1"
                fill="#35313C"
            />
            <circle
                cx="12"
                cy="12"
                r="1"
                fill="#35313C"
            />
            <circle
                cx="16"
                cy="12"
                r="1"
                fill="#35313C"
            />
        </svg>
    )
);
