// Auto Generated by @mashcard/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file ScreenOff basic/screen-off.svg
 * @author Auto Generated by MashCard
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'screen-off',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M14.5 2.5C15.0523 2.5 15.5 2.94772 15.5 3.5V8.5H20.5C21.0523 8.5 21.5 8.94772 21.5 9.5C21.5 10.0523 21.0523 10.5 20.5 10.5H14.5C13.9477 10.5 13.5 10.0523 13.5 9.5V3.5C13.5 2.94772 13.9477 2.5 14.5 2.5Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2 3C2 2.44772 2.44772 2 3 2H9C9.55228 2 10 2.44772 10 3C10 3.55228 9.55228 4 9 4H4V9C4 9.55228 3.55228 10 3 10C2.44772 10 2 9.55228 2 9V3Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M21 14C21.5523 14 22 14.4477 22 15V21C22 21.5523 21.5523 22 21 22H15C14.4477 22 14 21.5523 14 21C14 20.4477 14.4477 20 15 20H20V15C20 14.4477 20.4477 14 21 14Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2.5 14.5C2.5 13.9477 2.94772 13.5 3.5 13.5H9.5C10.0523 13.5 10.5 13.9477 10.5 14.5V20.5C10.5 21.0523 10.0523 21.5 9.5 21.5C8.94772 21.5 8.5 21.0523 8.5 20.5V15.5H3.5C2.94772 15.5 2.5 15.0523 2.5 14.5Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M21.7071 2.29289C22.0976 2.68342 22.0976 3.31658 21.7071 3.70711L15.2071 10.2071C14.8166 10.5976 14.1834 10.5976 13.7929 10.2071C13.4024 9.81658 13.4024 9.18342 13.7929 8.79289L20.2929 2.29289C20.6834 1.90237 21.3166 1.90237 21.7071 2.29289Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M10.2071 13.7929C10.5976 14.1834 10.5976 14.8166 10.2071 15.2071L3.70711 21.7071C3.31658 22.0976 2.68342 22.0976 2.29289 21.7071C1.90237 21.3166 1.90237 20.6834 2.29289 20.2929L8.79289 13.7929C9.18342 13.4024 9.81658 13.4024 10.2071 13.7929Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
