export const baseStyles = {
  lineHeight: '$2xl',
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  margin: 0,
  cursor: 'pointer',
  userSelect: 'none',
  border: 'none',
  borderRadius: '$2xs',
  paddingLeft: '$xl',
  paddingRight: '$xl',
  paddingTop: '$xs',
  paddingBottom: '$xs',
  fontWeight: '400',
  outline: 'none',
  verticalAlign: 'middle',
  whiteSpace: 'nowrap',
  touchAction: 'manipulation',
  transition: 'all .3s $ease-in-out'
}
