#!/usr/bin/env bash

YELLOW='\033[0;33m'
NC='\033[0m'

for d in $(yarn workspaces list | awk '{print $3}'); do
  if [[ $d == 'Done' ]]; then
    continue
  fi
  if [[ $d == '.' ]]; then
    package='the root package'
  else
    package=$d
  fi
  echo -e "${YELLOW}Checking dependencies for $package...${NC}"
  yarn depcheck $d
done
