import { FastifyPluginAsync } from 'fastify'
import fp from 'fastify-plugin'
import { NestFastifyApplication } from '@nestjs/platform-fastify'

const REQUEST_ID_HEADER = 'X-Request-Id'

const RequestIDPlugin: FastifyPluginAsync = async (fastify, _options) => {
  fastify.addHook('preHandler', async (req, reply) => {
    if (req.headers[REQUEST_ID_HEADER]) {
      // In kubernetes, the request id is generated by the ingress controller.
      req.id = req.headers[REQUEST_ID_HEADER]
    } else {
      // In other environments, we use the local reqId generated by fastify.
      req.headers[REQUEST_ID_HEADER] = req.id
    }
    // Append the request id to the response headers for tracking.
    void reply.header(REQUEST_ID_HEADER, req.id)
  })
}

export const requestIDRegister = async (app: NestFastifyApplication): Promise<void> => {
  await app.register(fp(RequestIDPlugin))
}
