export type Maybe<T> = T | null
export type InputMaybe<T> = Maybe<T>
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> }
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> }
/** All built-in and custom scalars, mapped to their actual values */
export interface Scalars {
  ID: string
  String: string
  Boolean: boolean
  Int: number
  Float: number
  /** AutoIncrement Primary Key */
  AutoIncrementID: string
  /** Represents non-fractional signed whole numeric values. Since the value may exceed the size of a 32-bit integer, it's encoded as a string. */
  BigInt: any
  /** Email Address */
  Email: string
  /** A valid http/https url or image uri */
  HttpUrl: string
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: any
  /** Represents untyped JSON */
  JSON: any
  /** UUID V4 */
  UUID: string
}

/** Available authentication authentication. */
export enum AuthMethod {
  /** Email and Password Authentication */
  EmailPassword = 'email_password',
  /**  Federated Authentication */
  Github = 'github',
  /**  Federated Authentication */
  GoogleOauth2 = 'google_oauth2'
}

export interface AuthorizationResult {
  __typename?: 'AuthorizationResult'
  /** Human-readable error message */
  message?: Maybe<Scalars['String']>
  /** Reasons of check failure */
  reasons?: Maybe<FailureReasons>
  /** Result of applying a policy rule */
  value: Scalars['Boolean']
}

export interface BlockAlias {
  __typename?: 'BlockAlias'
  key: Scalars['String']
  payload: Scalars['JSON']
}

export interface BlockAttachment {
  __typename?: 'BlockAttachment'
  /** height */
  height?: Maybe<Scalars['Int']>
  /** url or blob key */
  key?: Maybe<Scalars['String']>
  /** mode */
  mode?: Maybe<Scalars['String']>
  /** name */
  name?: Maybe<Scalars['String']>
  /** size */
  size?: Maybe<Scalars['Int']>
  /** source */
  source?: Maybe<Filesourcetype>
  /** type */
  type: Blocktype
  /** width */
  width?: Maybe<Scalars['Int']>
}

export interface BlockBaseObjectPermissions {
  __typename?: 'BlockBaseObjectPermissions'
  canShow: AuthorizationResult
}

export interface BlockColor {
  __typename?: 'BlockColor'
  /** string */
  color: Scalars['String']
  /** type */
  type?: Maybe<Blocktype>
}

/** GraphQL */
export type BlockCover = BlockColor | BlockImage

/** Autogenerated input type of BlockCreate */
export interface BlockCreateInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** parent id */
  parentId?: InputMaybe<Scalars['UUID']>
  /** title */
  title: Scalars['String']
}

/** Autogenerated return type of BlockCreate */
export interface BlockCreatePayload {
  __typename?: 'BlockCreatePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
  id: Scalars['UUID']
}

/** Autogenerated input type of BlockCreateShareLink */
export interface BlockCreateShareLinkInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block id */
  id: Scalars['UUID']
  /** share link target */
  target: ShareLinkInput[]
}

/** Autogenerated return type of BlockCreateShareLink */
export interface BlockCreateShareLinkPayload {
  __typename?: 'BlockCreateShareLinkPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of BlockCreateSnapshot */
export interface BlockCreateSnapshotInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block unique id */
  id: Scalars['UUID']
}

/** Autogenerated return type of BlockCreateSnapshot */
export interface BlockCreateSnapshotPayload {
  __typename?: 'BlockCreateSnapshotPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of BlockDuplicate */
export interface BlockDuplicateInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block unique id */
  id: Scalars['UUID']
}

/** Autogenerated return type of BlockDuplicate */
export interface BlockDuplicatePayload {
  __typename?: 'BlockDuplicatePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
  id: Scalars['UUID']
}

export interface BlockEmbedMeta {
  __typename?: 'BlockEmbedMeta'
  /** embedType */
  embedType?: Maybe<Embedtype>
  /** height */
  height?: Maybe<Scalars['Int']>
  /** url or blob key */
  key?: Maybe<Scalars['String']>
  /** mode */
  mode?: Maybe<Scalars['String']>
  /** name */
  name?: Maybe<Scalars['String']>
  /** size */
  size?: Maybe<Scalars['Int']>
  /** source */
  source?: Maybe<Filesourcetype>
  /** type */
  type?: Maybe<Scalars['String']>
  /** width */
  width?: Maybe<Scalars['Int']>
}

export interface BlockEmoji {
  __typename?: 'BlockEmoji'
  /** emoji */
  emoji: Scalars['String']
  /** name */
  name: Scalars['String']
  /** type */
  type?: Maybe<Blocktype>
}

/** Autogenerated input type of BlockHardDelete */
export interface BlockHardDeleteInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block unique id */
  id: Scalars['UUID']
}

/** Autogenerated return type of BlockHardDelete */
export interface BlockHardDeletePayload {
  __typename?: 'BlockHardDeletePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** GraphQL */
export type BlockIcon = BlockEmoji | BlockImage

export interface BlockImage {
  __typename?: 'BlockImage'
  /** height */
  height?: Maybe<Scalars['Int']>
  /** key */
  key?: Maybe<Scalars['String']>
  /** mode */
  mode?: Maybe<Scalars['String']>
  /** name */
  name?: Maybe<Scalars['String']>
  /** aspect ratio */
  ratio?: Maybe<Scalars['Float']>
  /** size */
  size?: Maybe<Scalars['Int']>
  /** type */
  source?: Maybe<Filesourcetype>
  /** type */
  type?: Maybe<Blocktype>
  /** width */
  width?: Maybe<Scalars['Int']>
}

export interface BlockInfo {
  __typename?: 'BlockInfo'
  /** space */
  collaborators: Space[]
  /** alias */
  enabledAlias?: Maybe<BlockAlias>
  /** icon */
  icon?: Maybe<BlockIcon>
  /** id */
  id: Scalars['UUID']
  /** is deleted */
  isDeleted: Scalars['Boolean']
  /** is master */
  isMaster: Scalars['Boolean']
  /** path */
  pathArray: BlockPath[]
  /** permission */
  permission?: Maybe<ShareLink>
  /** pin */
  pin: Scalars['Boolean']
  /** title */
  title: Scalars['String']
}

/** InputObject type of Class */
export interface BlockInput {
  /** attachments */
  attachments?: InputMaybe<Array<Scalars['String']>>
  /** content */
  content: Array<Scalars['JSON']>
  /** data */
  data?: InputMaybe<Scalars['JSON']>
  /** block unique id */
  id: Scalars['UUID']
  /** meta */
  meta?: InputMaybe<Scalars['JSON']>
  /** parent uuid */
  parentId?: InputMaybe<Scalars['UUID']>
  /** block sort */
  sort?: InputMaybe<Scalars['BigInt']>
  /** text */
  text: Scalars['String']
  /** block type */
  type: Scalars['String']
}

export interface BlockLink {
  __typename?: 'BlockLink'
  /** cover */
  cover?: Maybe<Scalars['String']>
  /** description */
  description?: Maybe<Scalars['String']>
  /** height */
  height?: Maybe<Scalars['Int']>
  /** key */
  key?: Maybe<Scalars['String']>
  /** mode */
  mode?: Maybe<Scalars['String']>
  /** name */
  name?: Maybe<Scalars['String']>
  /** size */
  size?: Maybe<Scalars['Int']>
  /** source */
  source?: Maybe<Filesourcetype>
  /** title */
  title?: Maybe<Scalars['String']>
  /** type */
  type: Scalars['String']
  /** width */
  width?: Maybe<Scalars['Int']>
}

export interface BlockMeta {
  __typename?: 'BlockMeta'
  /** attachment */
  attachment?: Maybe<BlockAttachment>
  /** cover */
  cover?: Maybe<BlockCover>
  /** embedMeta */
  embedMeta?: Maybe<BlockEmbedMeta>
  /** icon */
  icon?: Maybe<BlockIcon>
  /** image */
  image?: Maybe<BlockImage>
  /** Prosemirror builtin language */
  language?: Maybe<Scalars['String']>
  /** Prosemirror builtin level */
  level?: Maybe<Scalars['Int']>
  /** link */
  link?: Maybe<BlockLink>
  /** page */
  page?: Maybe<BlockPage>
  /** people */
  people?: Maybe<BlockPeople>
  /** Prosemirror builtin start */
  start?: Maybe<Scalars['String']>
  /** title */
  title?: Maybe<Scalars['String']>
}

/** Autogenerated input type of BlockMove */
export interface BlockMoveInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block unique id */
  id: Scalars['UUID']
  /** block sort */
  sort: Scalars['BigInt']
  /** target parent id */
  targetParentId?: InputMaybe<Scalars['UUID']>
}

/** Autogenerated return type of BlockMove */
export interface BlockMovePayload {
  __typename?: 'BlockMovePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

export interface BlockPage {
  __typename?: 'BlockPage'
  /** height */
  height?: Maybe<Scalars['Int']>
  /** icon */
  icon?: Maybe<Scalars['String']>
  /** key */
  key: Scalars['String']
  /** link */
  link: Scalars['String']
  /** mode */
  mode?: Maybe<Scalars['String']>
  /** name */
  name?: Maybe<Scalars['String']>
  /** size */
  size?: Maybe<Scalars['Int']>
  /** source */
  source?: Maybe<Filesourcetype>
  /** title */
  title?: Maybe<Scalars['String']>
  /** type */
  type?: Maybe<Blocktype>
  /** width */
  width?: Maybe<Scalars['Int']>
}

export interface BlockPath {
  __typename?: 'BlockPath'
  /** icon */
  icon?: Maybe<BlockIcon>
  /** icon */
  id: Scalars['UUID']
  /** cover */
  text: Scalars['String']
}

export interface BlockPeople {
  __typename?: 'BlockPeople'
  /** avatar */
  avatarUrl?: Maybe<Scalars['String']>
  /** height */
  height?: Maybe<Scalars['Int']>
  /** url or blob key */
  key?: Maybe<Scalars['String']>
  /** mode */
  mode?: Maybe<Scalars['String']>
  /** name */
  name?: Maybe<Scalars['String']>
  /** size */
  size?: Maybe<Scalars['Int']>
  /** source */
  source?: Maybe<Filesourcetype>
  /** type */
  type?: Maybe<Blocktype>
  /** key */
  domain: Scalars['String']
  /** width */
  width?: Maybe<Scalars['Int']>
}

/** Autogenerated input type of BlockPinOrUnpin */
export interface BlockPinOrUnpinInput {
  /** block id */
  blockId: Scalars['UUID']
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** pin */
  pin: Scalars['Boolean']
}

/** Autogenerated return type of BlockPinOrUnpin */
export interface BlockPinOrUnpinPayload {
  __typename?: 'BlockPinOrUnpinPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of BlockRename */
export interface BlockRenameInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block id */
  id: Scalars['UUID']
  /** New title */
  title: Scalars['String']
}

/** Autogenerated return type of BlockRename */
export interface BlockRenamePayload {
  __typename?: 'BlockRenamePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of BlockRestore */
export interface BlockRestoreInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block unique id */
  id: Scalars['UUID']
}

/** Autogenerated return type of BlockRestore */
export interface BlockRestorePayload {
  __typename?: 'BlockRestorePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

export interface BlockSnapshot {
  __typename?: 'BlockSnapshot'
  /** created at */
  createdAt: Scalars['ISO8601DateTime']
  /** object unique id */
  id: Scalars['AutoIncrementID']
  /** Snapshot name */
  name: Scalars['String']
  /** relative time */
  relativeTime: Scalars['String']
  /** Snapshot version */
  snapshotVersion: Scalars['Int']
}

/** Autogenerated input type of BlockSoftDelete */
export interface BlockSoftDeleteInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** block unique id */
  id: Scalars['UUID']
}

/** Autogenerated return type of BlockSoftDelete */
export interface BlockSoftDeletePayload {
  __typename?: 'BlockSoftDeletePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of BlockSyncBatch */
export interface BlockSyncBatchInput {
  blocks: BlockInput[]
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** deleted ids */
  deletedIds: Array<Scalars['UUID']>
  /** operator id */
  operatorId: Scalars['String']
  /** block root id */
  rootId: Scalars['UUID']
}

/** Autogenerated return type of BlockSyncBatch */
export interface BlockSyncBatchPayload {
  __typename?: 'BlockSyncBatchPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

export enum Blocktype {
  /** ATTACHMENT */
  Attachment = 'ATTACHMENT',
  /** COLOR */
  Color = 'COLOR',
  /** EMOJI */
  Emoji = 'EMOJI',
  /** IMAGE */
  Image = 'IMAGE',
  /** PAGE */
  Page = 'PAGE',
  /** PEOPLE */
  People = 'PEOPLE'
}

/** Autogenerated input type of CreateDirectUpload */
export interface CreateDirectUploadInput {
  /** block id */
  blockId?: InputMaybe<Scalars['UUID']>
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  input: DirectUploadInput
  type: Upload
}

/** Autogenerated return type of CreateDirectUpload */
export interface CreateDirectUploadPayload {
  __typename?: 'CreateDirectUploadPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  directUpload: DirectUpload
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of CreateOrUpdateSpace */
export interface CreateOrUpdateSpaceInput {
  /** Avatar signed id */
  avatarSignedId?: InputMaybe<Scalars['String']>
  /** bio */
  bio?: InputMaybe<Scalars['String']>
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** invite enable */
  inviteEnable?: InputMaybe<Scalars['Boolean']>
  /** invite secret */
  inviteSecret?: InputMaybe<Scalars['String']>
  /** space name */
  name?: InputMaybe<Scalars['String']>
  type: SpaceOperation
  /** domain */
  domain: Scalars['String']
}

/** Autogenerated return type of CreateOrUpdateSpace */
export interface CreateOrUpdateSpacePayload {
  __typename?: 'CreateOrUpdateSpacePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
  space?: Maybe<Space>
}

/** Represents direct upload credentials */
export interface DirectUpload {
  __typename?: 'DirectUpload'
  /** Created blob record key */
  blobKey: Scalars['String']
  /** Download url */
  downloadUrl: Scalars['String']
  /** HTTP request headers (JSON-encoded) */
  headers: Scalars['JSON']
  /** Blob signed id */
  signedId: Scalars['String']
  /** Upload URL */
  uploadUrl: Scalars['String']
  /** View url */
  viewUrl: Scalars['String']
}

/** File information required to prepare a direct upload */
export interface DirectUploadInput {
  /** File size (bytes) */
  byteSize: Scalars['Int']
  /** MD5 file checksum as base64 */
  checksum: Scalars['String']
  /** File content type */
  contentType: Scalars['String']
  /** Original file name */
  filename: Scalars['String']
  /** metadata */
  metadata?: InputMaybe<Scalars['JSON']>
}

export enum Embedtype {
  /** GALLERY */
  Gallery = 'GALLERY',
  /** LINK */
  Link = 'LINK',
  /** UPLOAD */
  Upload = 'UPLOAD'
}

export interface FailureReasons {
  __typename?: 'FailureReasons'
  /** JSON-encoded map of reasons */
  details: Scalars['String']
  /** Human-readable errors */
  fullMessages: Array<Scalars['String']>
}

export enum Filesourcetype {
  /** EXTERNAL */
  External = 'EXTERNAL',
  /** ORIGIN */
  Origin = 'ORIGIN'
}

export interface Formula {
  __typename?: 'Formula'
  /** block id */
  blockId: Scalars['UUID']
  /** dump value */
  cacheValue: Scalars['JSON']
  /** created at */
  createdAt: Scalars['Int']
  /** formula definition */
  definition: Scalars['String']
  /** object unique id */
  id: Scalars['UUID']
  /** formula name */
  name: Scalars['String']
  /** type */
  type: Scalars['String']
  /** updated at */
  updatedAt: Scalars['ISO8601DateTime']
  /** version */
  version: Scalars['Int']
}

/** Autogenerated input type of FormulaCreate */
export interface FormulaCreateInput {
  /** block id */
  blockId: Scalars['UUID']
  /** dump value */
  cacheValue?: InputMaybe<Scalars['JSON']>
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** definition */
  definition: Scalars['String']
  /** id */
  id: Scalars['UUID']
  /** name */
  name: Scalars['String']
  /** type */
  type?: InputMaybe<Scalars['String']>
  /** version */
  version?: InputMaybe<Scalars['Int']>
}

/** Autogenerated return type of FormulaCreate */
export interface FormulaCreatePayload {
  __typename?: 'FormulaCreatePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of FormulaDelete */
export interface FormulaDeleteInput {
  /** block id */
  blockId: Scalars['UUID']
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** id */
  id: Scalars['UUID']
}

/** Autogenerated return type of FormulaDelete */
export interface FormulaDeletePayload {
  __typename?: 'FormulaDeletePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of FormulaUpdate */
export interface FormulaUpdateInput {
  /** block id */
  blockId: Scalars['UUID']
  /** dump value */
  cacheValue?: InputMaybe<Scalars['JSON']>
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** definition */
  definition?: InputMaybe<Scalars['String']>
  /** id */
  id: Scalars['UUID']
  /** name */
  name?: InputMaybe<Scalars['String']>
  /** type */
  type?: InputMaybe<Scalars['String']>
  /** version */
  version?: InputMaybe<Scalars['Int']>
}

/** Autogenerated return type of FormulaUpdate */
export interface FormulaUpdatePayload {
  __typename?: 'FormulaUpdatePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of JoinSpace */
export interface JoinSpaceInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** invite secret */
  inviteSecret?: InputMaybe<Scalars['String']>
}

/** Autogenerated return type of JoinSpace */
export interface JoinSpacePayload {
  __typename?: 'JoinSpacePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

export enum MemberRole {
  /** ADMIN */
  Admin = 'admin',
  /** MEMBER */
  Member = 'member'
}

export enum MemberState {
  /** DISABLED */
  Disabled = 'disabled',
  /** ENABLED */
  Enabled = 'enabled'
}

/** Autogenerated return type of NewPatch */
export interface NewPatchPayload {
  __typename?: 'NewPatchPayload'
  patches: PatchBaseObject[]
  seq: Scalars['Int']
  state: Patchstate
}

export interface PatchBaseObject {
  __typename?: 'PatchBaseObject'
  id: Scalars['UUID']
  operatorId: Scalars['String']
  patchType: Patchtype
  path: Array<Scalars['UUID']>
  payload: Scalars['JSON']
}

export enum Patchstate {
  /** ACTIVE */
  Active = 'ACTIVE',
  /** DELETED */
  Deleted = 'DELETED',
  /** SUBSCRIBED */
  Subscribed = 'SUBSCRIBED'
}

export enum Patchtype {
  /** ADD */
  Add = 'ADD',
  /** DELETE */
  Delete = 'DELETE',
  /** UPDATE */
  Update = 'UPDATE'
}

/** Autogenerated input type of SpaceDestroy */
export interface SpaceDestroyInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** domain */
  domain: Scalars['String']
}

/** Autogenerated return type of SpaceDestroy */
export interface SpaceDestroyPayload {
  __typename?: 'SpaceDestroyPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of SpaceLeave */
export interface SpaceLeaveInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** User domain */
  userDomain: Scalars['String']
  /** Space domain */
  domain: Scalars['String']
}

/** Autogenerated return type of SpaceLeave */
export interface SpaceLeavePayload {
  __typename?: 'SpaceLeavePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Space operation types */
export enum SpaceOperation {
  /** CREATE */
  Create = 'CREATE',
  /** UPDATE */
  Update = 'UPDATE'
}

export enum Policytype {
  /** EDIT */
  Edit = 'edit',
  /** VIEW */
  View = 'view'
}

export interface RootMutation {
  __typename?: 'RootMutation'
  blockCreate?: Maybe<BlockCreatePayload>
  blockCreateShareLink?: Maybe<BlockCreateShareLinkPayload>
  blockCreateSnapshot?: Maybe<BlockCreateSnapshotPayload>
  blockDuplicate?: Maybe<BlockDuplicatePayload>
  blockHardDelete?: Maybe<BlockHardDeletePayload>
  blockMove?: Maybe<BlockMovePayload>
  blockPinOrUnpin?: Maybe<BlockPinOrUnpinPayload>
  blockRename?: Maybe<BlockRenamePayload>
  blockRestore?: Maybe<BlockRestorePayload>
  blockSoftDelete?: Maybe<BlockSoftDeletePayload>
  blockSyncBatch?: Maybe<BlockSyncBatchPayload>
  createDirectUpload?: Maybe<CreateDirectUploadPayload>
  createOrUpdateSpace?: Maybe<CreateOrUpdateSpacePayload>
  formulaCreate?: Maybe<FormulaCreatePayload>
  formulaDelete?: Maybe<FormulaDeletePayload>
  formulaUpdate?: Maybe<FormulaUpdatePayload>
  joinSpace?: Maybe<JoinSpacePayload>
  spaceDestroy?: Maybe<SpaceDestroyPayload>
  spaceLeave?: Maybe<SpaceLeavePayload>
  snapshotRestore?: Maybe<SnapshotRestorePayload>
  updateMember?: Maybe<UpdateMemberPayload>
  updateDomain?: Maybe<UpdateDomainPayload>
  userAppearanceUpdate?: Maybe<UserAppearanceUpdatePayload>
  /**
   *
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  userConfirmationEmailResend?: Maybe<UserConfirmationEmailResendPayload>
  /**
   *
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  userCreate?: Maybe<UserCreatePayload>
  /**
   *
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  userDestroy?: Maybe<UserDestroyPayload>
  /**
   *
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  userEmailPasswordSignIn?: Maybe<UserEmailPasswordSignInPayload>
  /**
   *
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  userForgetPasswordMailSend?: Maybe<UserForgetPasswordMailSendPayload>
  /**
   *
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  userPasswordReset?: Maybe<UserPasswordResetPayload>
  /**
   *
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  userSignOut?: Maybe<UserSignOutPayload>
}

export interface RootMutationBlockCreateArgs {
  input: BlockCreateInput
}

export interface RootMutationBlockCreateShareLinkArgs {
  input: BlockCreateShareLinkInput
}

export interface RootMutationBlockCreateSnapshotArgs {
  input: BlockCreateSnapshotInput
}

export interface RootMutationBlockDuplicateArgs {
  input: BlockDuplicateInput
}

export interface RootMutationBlockHardDeleteArgs {
  input: BlockHardDeleteInput
}

export interface RootMutationBlockMoveArgs {
  input: BlockMoveInput
}

export interface RootMutationBlockPinOrUnpinArgs {
  input: BlockPinOrUnpinInput
}

export interface RootMutationBlockRenameArgs {
  input: BlockRenameInput
}

export interface RootMutationBlockRestoreArgs {
  input: BlockRestoreInput
}

export interface RootMutationBlockSoftDeleteArgs {
  input: BlockSoftDeleteInput
}

export interface RootMutationBlockSyncBatchArgs {
  input: BlockSyncBatchInput
}

export interface RootMutationCreateDirectUploadArgs {
  input: CreateDirectUploadInput
}

export interface RootMutationCreateOrUpdateSpaceArgs {
  input: CreateOrUpdateSpaceInput
}

export interface RootMutationFormulaCreateArgs {
  input: FormulaCreateInput
}

export interface RootMutationFormulaDeleteArgs {
  input: FormulaDeleteInput
}

export interface RootMutationFormulaUpdateArgs {
  input: FormulaUpdateInput
}

export interface RootMutationJoinSpaceArgs {
  input: JoinSpaceInput
}

export interface RootMutationSpaceDestroyArgs {
  input: SpaceDestroyInput
}

export interface RootMutationSpaceLeaveArgs {
  input: SpaceLeaveInput
}

export interface RootMutationSnapshotRestoreArgs {
  input: SnapshotRestoreInput
}

export interface RootMutationUpdateMemberArgs {
  input: UpdateMemberInput
}

export interface RootMutationUpdateDomainArgs {
  input: UpdateDomainInput
}

export interface RootMutationUserAppearanceUpdateArgs {
  input: UserAppearanceUpdateInput
}

export interface RootMutationUserConfirmationEmailResendArgs {
  input: UserConfirmationEmailResendInput
}

export interface RootMutationUserCreateArgs {
  input: UserCreateInput
}

export interface RootMutationUserDestroyArgs {
  input: UserDestroyInput
}

export interface RootMutationUserEmailPasswordSignInArgs {
  input: UserEmailPasswordSignInInput
}

export interface RootMutationUserForgetPasswordMailSendArgs {
  input: UserForgetPasswordMailSendInput
}

export interface RootMutationUserPasswordResetArgs {
  input: UserPasswordResetInput
}

export interface RootMutationUserSignOutArgs {
  input: UserSignOutInput
}

export interface RootQuery {
  __typename?: 'RootQuery'
  /** return single block by id. */
  block?: Maybe<Block>
  blockInfo?: Maybe<BlockInfo>
  /** return all pins */
  blockPins?: Maybe<Pin[]>
  blockSearch?: Maybe<Block[]>
  /** return share links by block id. */
  blockShareLinks: ShareLink[]
  /** return snapshots by block id. */
  blockSnapshots?: Maybe<BlockSnapshot[]>
  childrenBlocks?: Maybe<Block[]>
  currentSpaceDomain: Scalars['String']
  /**
   * Check email available.
   * Required `context[:entrypoints]` is `[:internal]`.
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  emailAvailable: Validate_Result
  /**
   * provides a federated identity session data
   * Required `context[:entrypoints]` is `[:internal]`.
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  federatedIdentitySession: OmniauthSession
  formulas?: Maybe<Formula[]>
  /** Return information about current Brickdoc server instance. */
  metadata: Metadata
  pageBlocks?: Maybe<Block[]>
  /**
   * Check password available.
   * Required `context[:entrypoints]` is `[:internal]`.
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  passwordAvailable: Validate_Result
  /** return all plugins for space. */
  plugins: Plugin[]
  /** return current space for user. */
  space: Space
  /** return all space users */
  spaceMembers?: Maybe<Space_Member[]>
  /** search spaces */
  spaceSearch: Space[]
  /** return all spaces for user. */
  spaces: Space[]
  /** return preview box data of url */
  previewBox: Preview_Box
  spreadsheetChildren?: Maybe<SpreadsheetChildren>
  trashBlocks?: Maybe<Block[]>
  /** return images from unsplash by search */
  unsplashImage?: Maybe<Unsplash_Image[]>
  /**
   * Check domain available.
   * Required `context[:entrypoints]` is `[:internal]`.
   * Required `context[:entrypoints]` is `[:internal]`.
   */
  domainAvailable: Validate_Result
}

export interface RootQueryBlockArgs {
  id: Scalars['String']
}

export interface RootQueryBlockInfoArgs {
  id: Scalars['String']
  domain: Scalars['String']
}

export interface RootQueryBlockSearchArgs {
  input: Scalars['String']
  domain: Scalars['String']
}

export interface RootQueryBlockShareLinksArgs {
  id: Scalars['String']
}

export interface RootQueryBlockSnapshotsArgs {
  id: Scalars['String']
}

export interface RootQueryChildrenBlocksArgs {
  rootId: Scalars['String']
  snapshotVersion: Scalars['Int']
}

export interface RootQueryEmailAvailableArgs {
  email: Scalars['String']
}

export interface RootQueryFormulasArgs {
  domain: Scalars['String']
}

export interface RootQueryPageBlocksArgs {
  domain: Scalars['String']
}

export interface RootQueryPasswordAvailableArgs {
  password: Scalars['String']
}

export interface RootQuerySpaceArgs {
  domain: Scalars['String']
}

export interface RootQuerySpaceSearchArgs {
  input: Scalars['String']
}

export interface RootQueryPreviewBoxArgs {
  url: Scalars['String']
}

export interface RootQuerySpreadsheetChildrenArgs {
  parentId: Scalars['String']
}

export interface RootQueryTrashBlocksArgs {
  blockId?: InputMaybe<Scalars['UUID']>
  search?: InputMaybe<Scalars['String']>
  domain: Scalars['String']
}

export interface RootQueryUnsplashImageArgs {
  page?: InputMaybe<Scalars['Int']>
  perPage?: InputMaybe<Scalars['Int']>
  query?: InputMaybe<Scalars['String']>
}

export interface RootQueryDomainAvailableArgs {
  domain: Scalars['String']
}

export interface RootSubscription {
  __typename?: 'RootSubscription'
  newPatch: NewPatchPayload
}

export interface RootSubscriptionNewPatchArgs {
  docId: Scalars['UUID']
}

export interface ShareLink {
  __typename?: 'ShareLink'
  key: Scalars['String']
  policy: Policytype
  shareSpaceData: Space
  state: ShareLinkState
}

/** InputObject type of Class */
export interface ShareLinkInput {
  /** policy */
  policy: Policytype
  /** state type */
  state: ShareLinkState
  /** block unique id */
  domain: Scalars['String']
}

export enum ShareLinkState {
  /** DISABLED */
  Disabled = 'disabled',
  /** ENABLED */
  Enabled = 'enabled'
}

/** Autogenerated input type of SnapshotRestore */
export interface SnapshotRestoreInput {
  /** block id */
  blockId: Scalars['UUID']
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** integer */
  snapshotVersion: Scalars['Int']
}

/** Autogenerated return type of SnapshotRestore */
export interface SnapshotRestorePayload {
  __typename?: 'SnapshotRestorePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

export interface SpreadsheetChildren {
  __typename?: 'SpreadsheetChildren'
  /** blocks */
  blocks?: Maybe<Block[]>
}

/** Autogenerated input type of UpdateMember */
export interface UpdateMemberInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** role */
  role: MemberRole
  /** state */
  state: MemberState
  /** domain */
  domain: Scalars['String']
}

/** Autogenerated return type of UpdateMember */
export interface UpdateMemberPayload {
  __typename?: 'UpdateMemberPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of UpdateDomain */
export interface UpdateDomainInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** new domain */
  newDomain: Scalars['String']
  /** current domain */
  domain: Scalars['String']
}

/** Autogenerated return type of UpdateDomain */
export interface UpdateDomainPayload {
  __typename?: 'UpdateDomainPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Upload types */
export enum Upload {
  /** Account avatar */
  Avatar = 'AVATAR',
  /** Page block */
  Doc = 'DOC',
  /** Third */
  Third = 'THIRD'
}

/** Autogenerated input type of UserAppearanceUpdate */
export interface UserAppearanceUpdateInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** User's preferred language */
  locale?: InputMaybe<Scalars['String']>
  /** User's preferred timezone */
  timezone?: InputMaybe<Scalars['String']>
}

/** Autogenerated return type of UserAppearanceUpdate */
export interface UserAppearanceUpdatePayload {
  __typename?: 'UserAppearanceUpdatePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of UserConfirmationEmailResend */
export interface UserConfirmationEmailResendInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** User's email address */
  email: Scalars['Email']
}

/** Autogenerated return type of UserConfirmationEmailResend */
export interface UserConfirmationEmailResendPayload {
  __typename?: 'UserConfirmationEmailResendPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of UserCreate */
export interface UserCreateInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** User's email address */
  email?: InputMaybe<Scalars['Email']>
  /** User's preferred language */
  locale: Scalars['String']
  /** Human-readable name of the user */
  name: Scalars['String']
  /** user password */
  password?: InputMaybe<Scalars['String']>
  /** User's preferred timezone */
  timezone: Scalars['String']
  /** Like a username, Unique within this instance of Brickdoc. */
  domain: Scalars['String']
}

/** Autogenerated return type of UserCreate */
export interface UserCreatePayload {
  __typename?: 'UserCreatePayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
  isUserActive?: Maybe<Scalars['Boolean']>
  /** redirect url path when sig up successful */
  redirectPath?: Maybe<Scalars['String']>
}

/** Autogenerated input type of UserDestroy */
export interface UserDestroyInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
}

/** Autogenerated return type of UserDestroy */
export interface UserDestroyPayload {
  __typename?: 'UserDestroyPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of UserEmailPasswordSignIn */
export interface UserEmailPasswordSignInInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** User's email address */
  email: Scalars['Email']
  /** user password */
  password: Scalars['String']
  /** remember authentication session */
  remember: Scalars['Boolean']
}

/** Autogenerated return type of UserEmailPasswordSignIn */
export interface UserEmailPasswordSignInPayload {
  __typename?: 'UserEmailPasswordSignInPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
  /** redirect url path when sign in successful */
  redirectPath?: Maybe<Scalars['String']>
}

/** Autogenerated input type of UserForgetPasswordMailSend */
export interface UserForgetPasswordMailSendInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** User's email address */
  email: Scalars['Email']
}

/** Autogenerated return type of UserForgetPasswordMailSend */
export interface UserForgetPasswordMailSendPayload {
  __typename?: 'UserForgetPasswordMailSendPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of UserPasswordReset */
export interface UserPasswordResetInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
  /** Reset password */
  password: Scalars['String']
  /** Reset password token by Devise */
  token: Scalars['String']
}

/** Autogenerated return type of UserPasswordReset */
export interface UserPasswordResetPayload {
  __typename?: 'UserPasswordResetPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

/** Autogenerated input type of UserSignOut */
export interface UserSignOutInput {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>
}

/** Autogenerated return type of UserSignOut */
export interface UserSignOutPayload {
  __typename?: 'UserSignOutPayload'
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>
  /** Errors encountered during execution of the mutation. */
  errors: Array<Scalars['String']>
}

export interface Avatar {
  __typename?: 'avatar'
  /** download url */
  downloadUrl: Scalars['String']
  /** signed id */
  signedId: Scalars['String']
  /** url */
  url: Scalars['String']
}

/** ActiveStorage blobs */
export interface Blob {
  __typename?: 'blob'
  /** Blob key */
  blobKey: Scalars['String']
  /** Blob url */
  downloadUrl: Scalars['String']
  /** Blob url */
  url: Scalars['String']
}

/** Brickdoc Docs::Block */
export interface Block {
  __typename?: 'block'
  /** blobs */
  blobs?: Maybe<Blob[]>
  /** collaborators */
  collaborators: Array<Scalars['BigInt']>
  /** content */
  content: Array<Scalars['JSON']>
  data: Scalars['JSON']
  /** deleted_at */
  deletedAt?: Maybe<Scalars['ISO8601DateTime']>
  /** block first child sort */
  firstChildSort: Scalars['BigInt']
  /** object unique id */
  id: Scalars['UUID']
  meta: BlockMeta
  /** block next sort */
  nextSort: Scalars['BigInt']
  /** parent uuid */
  parentId?: Maybe<Scalars['UUID']>
  /** path */
  pathArray: BlockPath[]
  permissions: BlockBaseObjectPermissions
  /** root uuid */
  rootId: Scalars['UUID']
  /** block sort */
  sort: Scalars['BigInt']
  /** text */
  text: Scalars['String']
  /** block type */
  type: Scalars['String']
}

/** Brickdoc Global Configuration */
export interface Config {
  __typename?: 'config'
  /** Enable email and password authentication */
  accountsEmailPasswordAuth: Scalars['Boolean']
  /** Enabled federated identity providers */
  accountsFederatedProviders?: Maybe<FederatedProvider[]>
  /** Preferred Authentication authentication */
  accountsPreferredAuthMethod: AuthMethod
  /** User agreement link */
  userAgreementLink: Scalars['HttpUrl']
}

/** Accounts Federated Identity Provide Configuration */
export interface FederatedProvider {
  __typename?: 'federatedProvider'
  /** Provider Logo URI */
  logo: Scalars['HttpUrl']
  /** Provider Name */
  name: Scalars['String']
}

/** Represents information about the Brickdoc Server Instance. */
export interface Metadata {
  __typename?: 'metadata'
  /** Current available locales. */
  availableLocales: Select_Option[]
  availableTimezones: Array<Scalars['String']>
  /** Brickdoc Global Config */
  config: Config
  /** object unique id */
  id: Scalars['AutoIncrementID']
}

/** session[:omniauth] */
export interface OmniauthSession {
  __typename?: 'omniauthSession'
  hasSession: Scalars['Boolean']
  /** Human-readable name of the user */
  name?: Maybe<Scalars['String']>
  /** Provider Name */
  provider?: Maybe<Scalars['String']>
  /** Like a username, Unique within this instance of Brickdoc. */
  domain?: Maybe<Scalars['String']>
}

/** Brickdoc Docs::Pin */
export interface Pin {
  __typename?: 'pin'
  /** root uuid */
  blockId: Scalars['UUID']
  meta: BlockMeta
  /** text */
  text: Scalars['String']
}

/** Brickdoc Plugin. */
export interface Plugin {
  __typename?: 'plugin'
  /** Enabled */
  enabled: Scalars['Boolean']
  /** logo */
  logo: Scalars['String']
  /** metadata */
  metadata: Scalars['JSON']
  /** Plugin Name */
  name: Scalars['String']
  /** version */
  version: Scalars['String']
}

/** Brickdoc Space. */
export interface Space {
  __typename?: 'space'
  /** Space Avatar */
  avatarData?: Maybe<Avatar>
  /** public profile bio */
  bio?: Maybe<Scalars['String']>
  /** owner email */
  email?: Maybe<Scalars['String']>
  /** object unique id */
  id: Scalars['AutoIncrementID']
  /** enable invite feature */
  inviteEnable: Scalars['Boolean']
  /** invite secret */
  inviteSecret?: Maybe<Scalars['String']>
  /** Space Name */
  name?: Maybe<Scalars['String']>
  /** owner is current user */
  owned: Scalars['Boolean']
  /** personal */
  personal: Scalars['Boolean']
  /** Like a username, Unique within this instance of Brickdoc */
  domain: Scalars['String']
}

export interface Space_Member {
  __typename?: 'space_member'
  /** Space Avatar */
  avatarData?: Maybe<Avatar>
  /** owner email */
  email: Scalars['String']
  /** object unique id */
  id: Scalars['AutoIncrementID']
  /** Space Name */
  name: Scalars['String']
  /** role */
  role: MemberRole
  /** state */
  state: MemberState
  /** Like a username, Unique within this instance of Brickdoc */
  domain: Scalars['String']
}

export interface Preview_Box {
  __typename?: 'preview_box'
  /** preview cover */
  cover?: Maybe<Scalars['String']>
  /** preview description */
  description?: Maybe<Scalars['String']>
  /** preview conetent size */
  size?: Maybe<Scalars['String']>
  /** preview title */
  title: Scalars['String']
  /** preview conetent type */
  type?: Maybe<Scalars['String']>
  /** preview url */
  url: Scalars['String']
}

/** Option Object for BrickDesign Select Component. */
export interface Select_Option {
  __typename?: 'select_option'
  /** option label */
  label: Scalars['String']
  /** option value */
  value: Scalars['String']
}

/** Unspash image. */
export interface Unsplash_Image {
  __typename?: 'unsplash_image'
  /** url for full size image */
  fullUrl: Scalars['String']
  /** Image height */
  height?: Maybe<Scalars['Int']>
  /** Unsplash image id */
  id: Scalars['String']
  /** url for small size image */
  smallUrl: Scalars['String']
  /** username */
  username?: Maybe<Scalars['String']>
  /** Image width */
  width?: Maybe<Scalars['Int']>
}

export interface Validate_Result {
  __typename?: 'validate_result'
  /** error message */
  message: Scalars['String']
  /** Validate success */
  success: Scalars['Boolean']
}
