# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/accept_language/all/accept_language.rbi
#
# accept_language-2.0.2

module AcceptLanguage
  def self.parse(field); end
end
class AcceptLanguage::Matcher
  def any_other_langtag(*available_langtags); end
  def call(*available_langtags); end
  def drop_unacceptable(*available_langtags); end
  def excluded_langtags; end
  def initialize(**languages_range); end
  def preferred_langtags; end
  def unacceptable?(langtag); end
end
class AcceptLanguage::Parser
  def import(field); end
  def initialize(field); end
  def languages_range; end
  def match(*available_langtags); end
end
