# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actioncable/all/actioncable.rbi
#
# actioncable-7.0.3

module ActionCable
  def self.gem_version; end
  def self.server; end
  def self.version; end
  def server; end
  extend ActiveSupport::Autoload
end
module ActionCable::VERSION
end
module ActionCable::Helpers
end
module ActionCable::Helpers::ActionCableHelper
  def action_cable_meta_tag; end
end
class ActionCable::Engine < Rails::Engine
end
module ActionCable::SubscriptionAdapter
  extend ActiveSupport::Autoload
end
class ActionCable::SubscriptionAdapter::Base
end
module ActionCable::SubscriptionAdapter::ChannelPrefix
end
class ActionCable::SubscriptionAdapter::SubscriberMap
end
class ActionCable::SubscriptionAdapter::Redis < ActionCable::SubscriptionAdapter::Base
end
class ActionCable::SubscriptionAdapter::Redis::Listener < ActionCable::SubscriptionAdapter::SubscriberMap
end
module ActionCable::Server
  extend ActiveSupport::Autoload
end
module ActionCable::Server::Connections
end
module ActionCable::Server::Broadcasting
end
class ActionCable::Server::Broadcasting::Broadcaster
end
class ActionCable::Server::Configuration
end
class ActionCable::Server::Worker
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  include ActionCable::Server::Worker::ActiveRecordConnectionManagement
  include ActiveSupport::Callbacks
end
module ActionCable::Server::Worker::ActiveRecordConnectionManagement
  extend ActiveSupport::Concern
end
module ActionCable::Channel
  extend ActiveSupport::Autoload
end
module ActionCable::Channel::Callbacks
  extend ActiveSupport::Concern
  include ActiveSupport::Callbacks
end
module ActionCable::Channel::Callbacks::ClassMethods
end
module ActionCable::Channel::PeriodicTimers
  extend ActiveSupport::Concern
end
module ActionCable::Channel::PeriodicTimers::ClassMethods
end
module ActionCable::Channel::Streams
  extend ActiveSupport::Concern
end
module ActionCable::Channel::Naming
  extend ActiveSupport::Concern
end
module ActionCable::Channel::Naming::ClassMethods
end
module ActionCable::Channel::Broadcasting
  extend ActiveSupport::Concern
end
module ActionCable::Channel::Broadcasting::ClassMethods
end
class ActionCable::Channel::Base
  extend ActionCable::Channel::Broadcasting::ClassMethods
  extend ActionCable::Channel::Callbacks::ClassMethods
  extend ActionCable::Channel::Naming::ClassMethods
  extend ActionCable::Channel::PeriodicTimers::ClassMethods
  extend ActionPolicy::Channel::ClassMethods
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  extend ActiveSupport::Rescuable::ClassMethods
  include ActionCable::Channel::Broadcasting
  include ActionCable::Channel::Callbacks
  include ActionCable::Channel::Naming
  include ActionCable::Channel::PeriodicTimers
  include ActionCable::Channel::Streams
  include ActionPolicy::Channel
  include ActiveSupport::Callbacks
  include ActiveSupport::Rescuable
  include Sentry::Rails::ActionCableExtensions::Channel::Subscriptions
end
class ActionCable::Server::Base
  include ActionCable::Server::Broadcasting
  include ActionCable::Server::Connections
end
module ActionCable::Connection
  extend ActiveSupport::Autoload
end
module ActionCable::Connection::Identification
  extend ActiveSupport::Concern
end
module ActionCable::Connection::Identification::ClassMethods
end
module ActionCable::Connection::InternalChannel
  extend ActiveSupport::Concern
end
module ActionCable::Connection::Authorization
end
class ActionCable::Connection::Authorization::UnauthorizedError < StandardError
end
class ActionCable::Connection::Base
  extend ActionCable::Connection::Identification::ClassMethods
  extend ActiveSupport::Rescuable::ClassMethods
  include ActionCable::Connection::Authorization
  include ActionCable::Connection::Identification
  include ActionCable::Connection::InternalChannel
  include ActiveSupport::Rescuable
end
class ActionCable::Connection::ClientSocket
end
class ActionCable::Connection::MessageBuffer
end
class ActionCable::Connection::Stream
end
class ActionCable::Connection::StreamEventLoop
end
class ActionCable::Connection::Subscriptions
end
class ActionCable::Connection::TaggedLoggerProxy
end
class ActionCable::Connection::NonInferrableConnectionError < StandardError
end
module ActionCable::Connection::Assertions
end
class ActionCable::Connection::TestCookieJar < ActiveSupport::HashWithIndifferentAccess
end
class ActionCable::Connection::TestRequest < ActionDispatch::TestRequest
end
module ActionCable::Connection::TestConnection
end
class ActionCable::Connection::TestCase < ActiveSupport::TestCase
  extend ActionCable::Connection::TestCase::Behavior::ClassMethods
  extend ActiveSupport::Testing::ConstantLookup::ClassMethods
  include ActionCable::Connection::TestCase::Behavior
  include ActiveSupport::Testing::ConstantLookup
end
module ActionCable::Connection::TestCase::Behavior
  extend ActiveSupport::Concern
  include ActionCable::Connection::Assertions
  include ActiveSupport::Testing::ConstantLookup
end
module ActionCable::Connection::TestCase::Behavior::ClassMethods
end
class ActionCable::Connection::WebSocket
end
module ActionCable::TestHelper
end
class ActionCable::Channel::NonInferrableChannelError < StandardError
end
module ActionCable::Channel::ChannelStub
end
class ActionCable::Channel::ConnectionStub
end
class ActionCable::Channel::TestCase < ActiveSupport::TestCase
  extend ActionCable::Channel::TestCase::Behavior::ClassMethods
  extend ActiveSupport::Testing::ConstantLookup::ClassMethods
  include ActionCable::Channel::TestCase::Behavior
  include ActiveSupport::Testing::ConstantLookup
end
module ActionCable::Channel::TestCase::Behavior
  extend ActiveSupport::Concern
  include ActionCable::TestHelper
  include ActiveSupport::Testing::ConstantLookup
end
module ActionCable::Channel::TestCase::Behavior::ClassMethods
end
class ActionCable::RemoteConnections
end
class ActionCable::RemoteConnections::RemoteConnection
  extend ActionCable::Connection::Identification::ClassMethods
  include ActionCable::Connection::Identification
end
class ActionCable::RemoteConnections::RemoteConnection::InvalidIdentifiersError < StandardError
end
class ActionCable::SubscriptionAdapter::Inline < ActionCable::SubscriptionAdapter::Base
end
class ActionCable::SubscriptionAdapter::Async < ActionCable::SubscriptionAdapter::Inline
end
class ActionCable::SubscriptionAdapter::Async::AsyncSubscriberMap < ActionCable::SubscriptionAdapter::SubscriberMap
end
class ActionCable::SubscriptionAdapter::Test < ActionCable::SubscriptionAdapter::Async
end
class ActionCable::TestCase < ActiveSupport::TestCase
  include ActionCable::TestHelper
end
