# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actionview/all/actionview.rbi
#
# actionview-7.0.3

module ActionView
  def self.eager_load!; end
  def self.gem_version; end
  def self.version; end
  extend ActiveSupport::Autoload
end
module ActionView::VERSION
end
class ActionView::Railtie < Rails::Engine
end
class ActionView::LogSubscriber < ActiveSupport::LogSubscriber
end
module ActionView::Helpers
  extend ActiveSupport::Autoload
  extend ActiveSupport::Concern
  include ActionView::Helpers::ActiveModelHelper
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::AssetUrlHelper
  include ActionView::Helpers::AtomFeedHelper
  include ActionView::Helpers::CacheHelper
  include ActionView::Helpers::CaptureHelper
  include ActionView::Helpers::ControllerHelper
  include ActionView::Helpers::CspHelper
  include ActionView::Helpers::CsrfHelper
  include ActionView::Helpers::DateHelper
  include ActionView::Helpers::DebugHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormOptionsHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::JavaScriptHelper
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::OutputSafetyHelper
  include ActionView::Helpers::RenderingHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActiveSupport::Benchmarkable
end
module ActionView::Helpers::CaptureHelper
end
module ActionView::Helpers::OutputSafetyHelper
end
module ActionView::Helpers::TagHelper
  include ActionView::Helpers::CaptureHelper
  include ActionView::Helpers::OutputSafetyHelper
end
class ActionView::Helpers::TagHelper::TagBuilder
  include ActionView::Helpers::CaptureHelper
  include ActionView::Helpers::OutputSafetyHelper
end
module ActionView::Helpers::UrlHelper
  extend ActiveSupport::Concern
  include ActionView::Helpers::TagHelper
end
module ActionView::Helpers::UrlHelper::ClassMethods
end
module ActionView::Helpers::SanitizeHelper
  extend ActiveSupport::Concern
end
module ActionView::Helpers::SanitizeHelper::ClassMethods
end
module ActionView::Helpers::TextHelper
  extend ActiveSupport::Concern
  include ActionView::Helpers::OutputSafetyHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
end
class ActionView::Helpers::TextHelper::Cycle
end
module ActionView::Helpers::ActiveModelHelper
end
module ActionView::Helpers::ActiveModelInstanceTag
end
module ActionView::Helpers::AssetUrlHelper
end
module ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::AssetUrlHelper
  include ActionView::Helpers::TagHelper
end
module ActionView::Helpers::AtomFeedHelper
end
class ActionView::Helpers::AtomFeedHelper::AtomBuilder
end
class ActionView::Helpers::AtomFeedHelper::AtomFeedBuilder < ActionView::Helpers::AtomFeedHelper::AtomBuilder
end
module ActionView::Helpers::CacheHelper
end
class ActionView::Helpers::CacheHelper::UncacheableFragmentError < StandardError
end
module ActionView::Helpers::CacheHelper::CachingRegistry
  extend ActionView::Helpers::CacheHelper::CachingRegistry
end
module ActionView::Helpers::ControllerHelper
end
module ActionView::Helpers::CspHelper
end
module ActionView::Helpers::CsrfHelper
end
module ActionView::Helpers::DateHelper
end
class ActionView::Helpers::DateTimeSelector
  include ActionView::Helpers::TagHelper
end
class ActionView::Helpers::FormBuilder
  include ActionView::ModelNaming
end
module ActionView::Helpers::DebugHelper
  include ActionView::Helpers::TagHelper
end
module ActionView::Helpers::FormTagHelper
  extend ActiveSupport::Concern
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::UrlHelper
end
module ActionView::ModelNaming
end
module ActionView::RecordIdentifier
  extend ActionView::ModelNaming
  extend ActionView::RecordIdentifier
  include ActionView::ModelNaming
end
module ActionView::Helpers::FormHelper
  extend ActiveSupport::Concern
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::ModelNaming
  include ActionView::RecordIdentifier
end
module ActionView::Helpers::FormOptionsHelper
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TextHelper
end
module ActionView::Helpers::JavaScriptHelper
end
module ActionView::Helpers::NumberHelper
end
class ActionView::Helpers::NumberHelper::InvalidNumberError < StandardError
end
module ActionView::Helpers::RenderingHelper
end
module ActionView::Helpers::TranslationHelper
  extend ActiveSupport::Concern
  include ActionView::Helpers::TagHelper
end
module ActionView::CollectionCaching
  extend ActiveSupport::Concern
end
class ActionView::AbstractRenderer
end
module ActionView::AbstractRenderer::ObjectRendering
end
class ActionView::AbstractRenderer::RenderedCollection
end
class ActionView::AbstractRenderer::RenderedCollection::EmptyCollection
end
class ActionView::AbstractRenderer::RenderedTemplate
end
class ActionView::PartialRenderer < ActionView::AbstractRenderer
  include ActionView::CollectionCaching
end
class ActionView::Template
  extend ActionView::Template::Handlers
  extend ActiveSupport::Autoload
end
module ActionView::Template::Handlers
end
class ActionView::Template::Handlers::Raw
end
class ActionView::Template::Handlers::ERB
end
class ActionView::Template::Handlers::ERB::Erubi < Erubi::Engine
end
class ActionView::Template::Handlers::Html < ActionView::Template::Handlers::Raw
end
class ActionView::Template::Handlers::Builder
end
class ActionView::CacheExpiry
end
class ActionView::CacheExpiry::Executor
end
class ActionView::CacheExpiry::ViewModificationWatcher
end
module ActionView::ViewPaths
  extend ActiveSupport::Concern
end
module ActionView::ViewPaths::ClassMethods
end
class ActionView::I18nProxy < I18n::Config
end
module ActionView::Rendering
  extend ActiveSupport::Concern
  include ActionView::ViewPaths
end
module ActionView::Rendering::ClassMethods
end
module ActionView::Layouts
  extend ActiveSupport::Concern
  include ActionView::Rendering
end
module ActionView::Layouts::ClassMethods
end
module ActionView::Layouts::ClassMethods::LayoutConditions
end
class ActionView::PathSet
  include Enumerable
end
class ActionView::TemplatePath
end
class ActionView::Resolver
end
class ActionView::Resolver::PathParser
end
class ActionView::FileSystemResolver < ActionView::Resolver
end
module ActionView::RoutingUrlFor
end
module ActionView::Context
end
class ActionView::LookupContext
  include ActionView::LookupContext::Accessors
  include ActionView::LookupContext::DetailsCache
  include ActionView::LookupContext::ViewPaths
end
module ActionView::LookupContext::Accessors
end
class ActionView::LookupContext::DetailsKey
end
module ActionView::LookupContext::DetailsCache
end
module ActionView::LookupContext::ViewPaths
end
module ActionView::Template::Types
end
class ActionView::Template::Types::Type
end
class ActionView::Base
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionCable::Helpers::ActionCableHelper
  include ActionView::Helpers
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include Devise::Controllers::UrlHelpers
  include Devise::OmniAuth::UrlHelpers
  include ViteRails::TagHelpers
end
class ActionView::RenderParser
end
module ActionView::RenderParser::RipperASTParser
  extend ActionView::RenderParser::RipperASTParser
end
class ActionView::RenderParser::RipperASTParser::Node < Array
end
class ActionView::RenderParser::RipperASTParser::NodeParser < Ripper
end
class ActionView::RenderParser::RipperASTParser::RenderCallExtractor < ActionView::RenderParser::RipperASTParser::NodeParser
end
class ActionView::DependencyTracker
  extend ActiveSupport::Autoload
end
class ActionView::DependencyTracker::ERBTracker
end
class ActionView::Digestor
end
class ActionView::Digestor::Node
end
class ActionView::Digestor::Partial < ActionView::Digestor::Node
end
class ActionView::Digestor::Missing < ActionView::Digestor::Node
end
class ActionView::Digestor::Injected < ActionView::Digestor::Node
end
class ActionView::Digestor::NullLogger
end
class ActionView::ActionViewError < StandardError
end
class ActionView::EncodingError < StandardError
end
class ActionView::WrongEncodingError < ActionView::EncodingError
end
class ActionView::MissingTemplate < ActionView::ActionViewError
  include DidYouMean::Correctable
end
class ActionView::MissingTemplate::Results
end
class ActionView::Template::Error < ActionView::ActionViewError
end
class ActionView::SyntaxErrorInTemplate < ActionView::Template::Error
end
class ActionView::Template::RawFile
end
class ActionView::Template::HTML
end
class ActionView::Template::Inline < ActionView::Template
end
module ActionView::Template::Sources
  extend ActiveSupport::Autoload
end
class ActionView::Template::Text
end
class ActionView::UnboundTemplate
end
class ActionView::TestCase < ActiveSupport::TestCase
  extend AbstractController::Helpers::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  extend ActionView::TestCase::Behavior::ClassMethods
  extend ActiveSupport::Testing::ConstantLookup::ClassMethods
  include AbstractController::Helpers
  include ActionView::Helpers
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::TestCase::Behavior
  include ActiveSupport::Testing::ConstantLookup
  include Rails::Dom::Testing::Assertions
end
class ActionView::TestCase::TestController < ActionController::Base
  include ActionDispatch::Routing::UrlFor
  include ActionDispatch::TestProcess
  include Anonymous_Module_22
end
module ActionView::TestCase::TestController::HelperMethods
  include ActionController::Base::HelperMethods
  include ApplicationHelper
  include DeviseHelper
end
module ActionView::TestCase::Behavior
  extend ActiveSupport::Concern
  include AbstractController::Helpers
  include ActionController::TemplateAssertions
  include ActionDispatch::Assertions
  include ActionDispatch::Routing::PolymorphicRoutes
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::RecordIdentifier
  include ActionView::RoutingUrlFor
  include ActiveSupport::Testing::ConstantLookup
  include Rails::Dom::Testing::Assertions
end
module ActionView::TestCase::Behavior::ClassMethods
end
class ActionView::TestCase::Behavior::RenderedViewsCollection
end
module ActionView::TestCase::Behavior::Locals
end
module ActionView::TestCase::HelperMethods
end
