# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/brickdoc_settings/all/brickdoc_settings.rbi
#
# brickdoc_settings-0.0.1

module BrickdocSettings
end
