# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cloak-rb/all/cloak-rb.rbi
#
# cloak-rb-0.1.1

module Cloak
  def self.generate_key; end
end
module Cloak::Utils
  def create_encryptor(key); end
  def decrypt_element(value); end
  def decrypt_field(key, field); end
  def decrypt_hll_element(value); end
  def decrypt_key(key); end
  def decrypt_member(value); end
  def decrypt_value(value); end
  def encrypt_element(value); end
  def encrypt_field(key, field); end
  def encrypt_hll_element(value); end
  def encrypt_key(key); end
  def encrypt_member(value); end
  def encrypt_value(value); end
  def to_binary(value); end
end
class Cloak::Error < StandardError
end
