# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/declarative/all/declarative.rbi
#
# declarative-0.0.20

module Declarative
end
class Declarative::Definitions < Hash
end
class Declarative::Definitions::Definition
end
class Declarative::Defaults
end
class Declarative::Variables
end
class Declarative::Variables::Proc < Proc
end
module Declarative::DeepDup
end
class Declarative::Heritage < Array
end
module Declarative::Heritage::DSL
end
module Declarative::Heritage::Inherited
end
module Declarative::Heritage::Included
end
module Declarative::Schema
end
module Declarative::Schema::DSL
end
module Declarative::Schema::Feature
end
