# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/default_value_for/all/default_value_for.rbi
#
# default_value_for-fe7ab1bd4a43

module DefaultValueFor
  def self.initialize_active_record_extensions; end
  def self.initialize_railtie; end
end
class DefaultValueFor::Railtie < Rails::Railtie
end
class DefaultValueFor::NormalValueContainer
  def evaluate(instance); end
  def initialize(value); end
end
class DefaultValueFor::BlockValueContainer
  def evaluate(instance); end
  def initialize(block); end
end
module DefaultValueFor::ClassMethods
  def default_value_for(attribute, options = nil, &block); end
  def default_values(values); end
end
module DefaultValueFor::DelayedClassMethods
  def _all_default_attribute_values; end
  def _all_default_attribute_values_not_allowing_nil; end
end
module DefaultValueFor::InstanceMethods
  def attributes_for_create(attribute_names); end
  def initialize(attributes = nil, options = nil); end
  def set_default_values; end
end
