# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/devise-async/all/devise-async.rbi
#
# devise-async-1.0.0

module Devise
end
module Devise::Models
end
module Devise::Models::Async
  def deliver_mail_later(notification, model, args); end
  def devise_pending_notifications; end
  def send_devise_notification(notification, *args); end
  def send_devise_pending_notifications; end
  extend ActiveSupport::Concern
end
module Devise::Async
  def enabled; end
  def enabled=(val); end
  def self.enabled; end
  def self.enabled=(val); end
  def self.setup; end
end
class Devise::Mapping
  def async?; end
end
