# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/flipper-active_record/all/flipper-active_record.rbi
#
# flipper-active_record-0.24.1

module Flipper
end
module Flipper::Adapters
end
class Flipper::Adapters::ActiveRecord
  extend Flipper::Adapter::ClassMethods
  include Flipper::Adapter
end
module Flipper::Adapters::ActiveRecord::Feature::GeneratedAttributeMethods
end
class Flipper::Adapters::ActiveRecord::Feature < ActiveRecord::Base
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedAttributeMethods
end
module Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods
end
class Flipper::Adapters::ActiveRecord::Feature::ActiveRecord_Relation < ActiveRecord::Relation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
module Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Feature::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Feature::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Feature::ActiveRecord_DisableJoinsAssociationRelation < ActiveRecord::DisableJoinsAssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
module Flipper::Adapters::ActiveRecord::Gate::GeneratedAttributeMethods
end
class Flipper::Adapters::ActiveRecord::Gate < ActiveRecord::Base
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedAttributeMethods
end
module Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods
end
class Flipper::Adapters::ActiveRecord::Gate::ActiveRecord_Relation < ActiveRecord::Relation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
module Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Gate::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Gate::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Gate::ActiveRecord_DisableJoinsAssociationRelation < ActiveRecord::DisableJoinsAssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
