# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/get_process_mem/all/get_process_mem.rbi
#
# get_process_mem-0.2.7

class GetProcessMem
  def bytes; end
  def darwin_memory; end
  def gb(b = nil); end
  def initialize(pid = nil); end
  def inspect; end
  def kb(b = nil); end
  def linux?; end
  def linux_memory(file = nil); end
  def linux_status_memory(file = nil); end
  def mb(b = nil); end
  def number_to_bigdecimal(value); end
  def pid; end
  def ps_memory; end
  def self.number_to_bigdecimal(value); end
end
class GetProcessMem::Darwin
  def proc_pidinfo(*arg0); end
  def self.get_proc_pidinfo(pid); end
  def self.proc_pidinfo(*arg0); end
  def self.resident_size(pid); end
  extend FFI::Library
end
class GetProcessMem::Darwin::TaskInfo < FFI::Struct
end
