# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/google-apis-iamcredentials_v1/all/google-apis-iamcredentials_v1.rbi
#
# google-apis-iamcredentials_v1-0.10.0

module Google
end
module Google::Apis
end
module Google::Apis::IamcredentialsV1
end
class Google::Apis::IamcredentialsV1::IAMCredentialsService < Google::Apis::Core::BaseService
end
class Google::Apis::IamcredentialsV1::GenerateAccessTokenRequest
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::GenerateAccessTokenResponse
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::GenerateIdTokenRequest
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::GenerateIdTokenResponse
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::SignBlobRequest
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::SignBlobResponse
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::SignJwtRequest
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::SignJwtResponse
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::IamcredentialsV1::GenerateAccessTokenRequest::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::IamcredentialsV1::GenerateAccessTokenResponse::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::IamcredentialsV1::GenerateIdTokenRequest::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::IamcredentialsV1::GenerateIdTokenResponse::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::IamcredentialsV1::SignBlobRequest::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::IamcredentialsV1::SignBlobResponse::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::IamcredentialsV1::SignJwtRequest::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::IamcredentialsV1::SignJwtResponse::Representation < Google::Apis::Core::JsonRepresentation
end
