# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/google-apis-core/all/google-apis-core.rbi
#
# google-apis-core-0.5.0

module Google
end
module Google::Apis
end
module Google::Apis::Core
end
class Google::Apis::ClientOptions < Struct
end
class Google::Apis::RequestOptions < Struct
end
class Google::Apis::Error < StandardError
end
class Google::Apis::TransmissionError < Google::Apis::Error
end
class Google::Apis::RedirectError < Google::Apis::Error
end
class Google::Apis::ClientError < Google::Apis::Error
end
class Google::Apis::RateLimitError < Google::Apis::Error
end
class Google::Apis::ProjectNotLinkedError < Google::Apis::Error
end
class Google::Apis::AuthorizationError < Google::Apis::Error
end
class Google::Apis::ServerError < Google::Apis::Error
end
class Google::Apis::BatchError < Google::Apis::Error
end
module Google::Apis::Core::Logging
end
class Google::Apis::Core::HttpCommand
  include Google::Apis::Core::Logging
end
class Google::Apis::Core::ApiCommand < Google::Apis::Core::HttpCommand
end
class Google::Apis::Core::JsonPart
end
class Google::Apis::Core::FilePart
end
class Google::Apis::Core::Multipart
end
class Google::Apis::Core::BaseUploadCommand < Google::Apis::Core::ApiCommand
end
class Google::Apis::Core::RawUploadCommand < Google::Apis::Core::BaseUploadCommand
end
class Google::Apis::Core::MultipartUploadCommand < Google::Apis::Core::BaseUploadCommand
end
class Google::Apis::Core::ResumableUploadCommand < Google::Apis::Core::BaseUploadCommand
end
class Google::Apis::Core::DownloadCommand < Google::Apis::Core::ApiCommand
end
class Google::Apis::Core::CompositeIO
end
class Google::Apis::Core::BatchCommand < Google::Apis::Core::HttpCommand
end
class Google::Apis::Core::BatchUploadCommand < Google::Apis::Core::BatchCommand
end
class Google::Apis::Core::CallSerializer
end
class Google::Apis::Core::CallDeserializer
end
class Google::Apis::Core::PagedResults
  include Enumerable
end
class Google::Apis::Core::BaseService
  include Google::Apis::Core::Logging
end
module Google::Apis::Core::JsonRepresentationSupport
end
module Google::Apis::Core::JsonRepresentationSupport::JsonSupport
end
class Google::Apis::Core::JsonRepresentation < Representable::Decorator
  extend Google::Apis::Core::JsonRepresentationSupport::JsonSupport
  extend Representable::ClassMethods
  extend Representable::Declarative
  extend Representable::ForCollection
  extend Representable::JSON::ClassMethods
  extend Representable::ModuleExtensions
  extend Representable::Represent
  include Google::Apis::Core::JsonRepresentationSupport
  include Representable
  include Representable::JSON
end
module Google::Apis::Core::JsonObjectSupport
end
module Google::Apis::Core::JsonObjectSupport::ClassMethods
end
module Google::Apis::Core::Hashable
end
