# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/google-apis-storage_v1/all/google-apis-storage_v1.rbi
#
# google-apis-storage_v1-0.14.0

module Google
end
module Google::Apis
end
module Google::Apis::StorageV1
end
class Google::Apis::StorageV1::StorageService < Google::Apis::Core::BaseService
end
class Google::Apis::StorageV1::Bucket
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Autoclass
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Billing
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::CorsConfiguration
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Encryption
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::IamConfiguration
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::IamConfiguration::BucketPolicyOnly
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::IamConfiguration::UniformBucketLevelAccess
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Lifecycle
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Lifecycle::Rule
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Lifecycle::Rule::Action
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Lifecycle::Rule::Condition
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Logging
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Owner
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::RetentionPolicy
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Versioning
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Website
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::BucketAccessControl
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::BucketAccessControl::ProjectTeam
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::BucketAccessControls
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Buckets
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Channel
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::ComposeRequest
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::ComposeRequest::SourceObject
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::ComposeRequest::SourceObject::ObjectPreconditions
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Expr
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::HmacKey
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::HmacKeyMetadata
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::HmacKeysMetadata
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Notification
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Notifications
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Object
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Object::CustomerEncryption
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Object::Owner
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::ObjectAccessControl
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::ObjectAccessControl::ProjectTeam
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::ObjectAccessControls
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Objects
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Policy
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Policy::Binding
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::RewriteResponse
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::ServiceAccount
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::TestIamPermissionsResponse
  extend Google::Apis::Core::JsonObjectSupport::ClassMethods
  include Google::Apis::Core::Hashable
  include Google::Apis::Core::JsonObjectSupport
end
class Google::Apis::StorageV1::Bucket::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Autoclass::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Billing::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::CorsConfiguration::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Encryption::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::IamConfiguration::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::IamConfiguration::BucketPolicyOnly::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::IamConfiguration::UniformBucketLevelAccess::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Lifecycle::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Lifecycle::Rule::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Lifecycle::Rule::Action::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Lifecycle::Rule::Condition::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Logging::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Owner::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::RetentionPolicy::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Versioning::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Bucket::Website::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::BucketAccessControl::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::BucketAccessControl::ProjectTeam::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::BucketAccessControls::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Buckets::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Channel::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::ComposeRequest::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::ComposeRequest::SourceObject::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::ComposeRequest::SourceObject::ObjectPreconditions::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Expr::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::HmacKey::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::HmacKeyMetadata::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::HmacKeysMetadata::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Notification::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Notifications::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Object::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Object::CustomerEncryption::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Object::Owner::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::ObjectAccessControl::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::ObjectAccessControl::ProjectTeam::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::ObjectAccessControls::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Objects::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Policy::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::Policy::Binding::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::RewriteResponse::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::ServiceAccount::Representation < Google::Apis::Core::JsonRepresentation
end
class Google::Apis::StorageV1::TestIamPermissionsResponse::Representation < Google::Apis::Core::JsonRepresentation
end
