# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/google-cloud-env/all/google-cloud-env.rbi
#
# google-cloud-env-1.6.0

module Google
end
module Google::Cloud
  def self.env; end
end
class Google::Cloud::Env
  def app_engine?; end
  def app_engine_flexible?; end
  def app_engine_memory_mb; end
  def app_engine_service_id; end
  def app_engine_service_name; end
  def app_engine_service_version; end
  def app_engine_standard?; end
  def cloud_shell?; end
  def compute_engine?; end
  def connection; end
  def container_engine?; end
  def container_engine_cluster_name; end
  def container_engine_namespace_id; end
  def env; end
  def initialize(env: nil, host: nil, connection: nil, metadata_cache: nil, open_timeout: nil, request_timeout: nil, retry_count: nil, retry_interval: nil, retry_backoff_factor: nil, retry_max_interval: nil); end
  def instance_attribute(key); end
  def instance_attribute_keys; end
  def instance_description; end
  def instance_machine_type; end
  def instance_name; end
  def instance_tags; end
  def instance_zone; end
  def knative?; end
  def knative_service_id; end
  def knative_service_name; end
  def knative_service_revision; end
  def kubernetes_engine?; end
  def kubernetes_engine_cluster_name; end
  def kubernetes_engine_namespace_id; end
  def lookup_metadata(type, entry); end
  def metadata?; end
  def metadata_cache; end
  def numeric_project_id; end
  def project_id; end
  def raw_compute_engine?; end
  def retry_or_fail_with(error_result); end
  def self.get; end
end
