# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/google-cloud-kms/all/google-cloud-kms.rbi
#
# google-cloud-kms-2.3.0

module Google
end
module Google::Cloud
end
module Google::Cloud::Kms
  def self.configure; end
  def self.ekm_service(version: nil, &block); end
  def self.iam_policy(version: nil, &block); end
  def self.key_management_service(version: nil, &block); end
end
