# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mail/all/mail.rbi
#
# mail-2.7.1

module Mail
end
class Mail::Ruby19
end
class Mail::Ruby19::StrictCharsetEncoder
end
class Mail::Ruby19::BestEffortCharsetEncoder
end
module Mail::VERSION
end
class String
end
class Mail::IndifferentHash < Hash
end
module Mail::Multibyte
end
module Mail::Multibyte::Unicode
  extend Mail::Multibyte::Unicode
end
class Mail::Multibyte::Unicode::Codepoint
end
class Mail::Multibyte::Unicode::UnicodeDatabase
end
class Mail::Multibyte::Chars
  include Comparable
end
class Mail::Multibyte::EncodingError < StandardError
end
module Mail::Constants
end
module Mail::Utilities
  include Mail::Constants
end
class Mail::Configuration
  extend Singleton::SingletonClassMethods
  include Singleton
end
class Mail::Retriever
end
class Mail::Message
  include Mail::Constants
  include Mail::Utilities
end
class Mail::Part < Mail::Message
end
class Mail::Header
  include Enumerable
  include Mail::Constants
  include Mail::Utilities
end
class Mail::PartsList < Anonymous_Delegator_69
end
class Mail::AttachmentsList < Array
end
class Mail::Body
end
class Mail::AddressContainer < Array
end
module Mail::CommonAddress
end
module Mail::CommonField
  include Mail::Constants
end
class Mail::StructuredField
  include Mail::CommonField
  include Mail::Utilities
end
class Mail::ToField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::CcField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::BccField < Mail::StructuredField
  include Mail::CommonAddress
end
module Mail::CommonMessageId
end
class Mail::MessageIdField < Mail::StructuredField
  include Mail::CommonMessageId
end
class Mail::InReplyToField < Mail::StructuredField
  include Mail::CommonMessageId
end
class Mail::ReferencesField < Mail::StructuredField
  include Mail::CommonMessageId
end
class Mail::UnstructuredField
  include Mail::CommonField
  include Mail::Utilities
end
class Mail::SubjectField < Mail::UnstructuredField
end
class Mail::CommentsField < Mail::UnstructuredField
end
class Mail::KeywordsField < Mail::StructuredField
end
module Mail::CommonDate
end
class Mail::DateField < Mail::StructuredField
  include Mail::CommonDate
end
class Mail::FromField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::SenderField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ReplyToField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ResentDateField < Mail::StructuredField
  include Mail::CommonDate
end
class Mail::ResentFromField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ResentSenderField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ResentToField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ResentCcField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ResentBccField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ResentMessageIdField < Mail::StructuredField
  include Mail::CommonMessageId
end
class Mail::ReturnPathField < Mail::StructuredField
  include Mail::CommonAddress
end
class Mail::ReceivedField < Mail::StructuredField
end
class Mail::MimeVersionField < Mail::StructuredField
end
class Mail::ContentTransferEncodingField < Mail::StructuredField
end
class Mail::ContentDescriptionField < Mail::UnstructuredField
end
class Mail::ParameterHash < Mail::IndifferentHash
  include Mail::Utilities
end
class Mail::ContentDispositionField < Mail::StructuredField
end
class Mail::ContentTypeField < Mail::StructuredField
end
class Mail::ContentIdField < Mail::StructuredField
end
class Mail::ContentLocationField < Mail::StructuredField
end
class Mail::Field
  include Comparable
  include Mail::Utilities
end
class Mail::Field::FieldError < StandardError
end
class Mail::Field::ParseError < Mail::Field::FieldError
end
class Mail::Field::NilParseError < Mail::Field::ParseError
end
class Mail::Field::IncompleteParseError < Mail::Field::ParseError
end
class Mail::Field::SyntaxError < Mail::Field::FieldError
end
class Mail::FieldList < Array
  include Enumerable
end
class Mail::Envelope < Mail::StructuredField
end
class Mail::UnknownEncodingType < StandardError
end
module Mail::Encodings
  extend Mail::Utilities
  include Mail::Constants
end
class Mail::Encodings::TransferEncoding
end
class Mail::Encodings::Identity < Mail::Encodings::TransferEncoding
end
class Mail::Encodings::Binary < Mail::Encodings::Identity
end
class Mail::Encodings::EightBit < Mail::Encodings::Binary
end
class Mail::Encodings::SevenBit < Mail::Encodings::EightBit
end
class Mail::Encodings::Base64 < Mail::Encodings::SevenBit
end
class Mail::Encodings::QuotedPrintable < Mail::Encodings::SevenBit
end
class Mail::Encodings::UnixToUnix < Mail::Encodings::TransferEncoding
end
module Mail::Matchers
end
class Mail::Matchers::HasSentEmailMatcher
end
class Mail::Matchers::AnyAttachmentMatcher
end
class Mail::Matchers::AttachmentFilenameMatcher
end
module Mail::CheckDeliveryParams
end
class Mail::TestMailer
end
class Mail::SMTP
end
class Mail::FileDelivery
end
class Mail::Sendmail
end
module Mail::ParserTools
end
module Mail::Parsers
end
module Mail::Parsers::ContentDispositionParser
  extend Mail::ParserTools
end
module Mail::Parsers::ContentLocationParser
  extend Mail::ParserTools
end
module Mail::Parsers::ContentTransferEncodingParser
  extend Mail::ParserTools
end
module Mail::Parsers::ContentTypeParser
  extend Mail::ParserTools
end
module Mail::Parsers::DateTimeParser
  extend Mail::ParserTools
end
module Mail::Parsers::EnvelopeFromParser
  extend Mail::ParserTools
end
module Mail::Parsers::MessageIdsParser
  extend Mail::ParserTools
end
module Mail::Parsers::MimeVersionParser
  extend Mail::ParserTools
end
class Mail::Parsers::PhraseListsParser
  extend Mail::ParserTools
end
module Mail::Parsers::ReceivedParser
  extend Mail::ParserTools
end
module Mail::Parsers::AddressListsParser
  extend Mail::ParserTools
end
class Mail::Address
  include Mail::Utilities
end
