# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth-github/all/omniauth-github.rbi
#
# omniauth-github-2.0.0

module OmniAuth
end
module OmniAuth::GitHub
end
module OmniAuth::Strategies
end
class OmniAuth::Strategies::GitHub < OmniAuth::Strategies::OAuth2
  extend OmniAuth::Strategy::ClassMethods
end
