# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth-oauth2/all/omniauth-oauth2.rbi
#
# omniauth-oauth2-1.7.2

module OmniAuth
end
module OmniAuth::OAuth2
end
module OmniAuth::Strategies
end
class OmniAuth::Strategies::OAuth2
  extend OmniAuth::Strategy::ClassMethods
  include OmniAuth::Strategy
end
class OmniAuth::Strategies::OAuth2::CallbackError < StandardError
end
