# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/retriable/all/retriable.rbi
#
# retriable-3.1.2

module Retriable
end
class Retriable::ExponentialBackoff
end
class Retriable::Config
end
