# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/shoulda-matchers/all/shoulda-matchers.rbi
#
# shoulda-matchers-5.1.0

module Shoulda
end
module Shoulda::Matchers
  extend Shoulda::Matchers::WordWrap
end
class Shoulda::Matchers::Configuration
end
module Shoulda::Matchers::Doublespeak
end
class Shoulda::Matchers::Doublespeak::Double
end
class Shoulda::Matchers::Doublespeak::DoubleCollection
end
module Shoulda::Matchers::Doublespeak::DoubleImplementationRegistry
end
class Shoulda::Matchers::Doublespeak::MethodCall
end
class Shoulda::Matchers::Doublespeak::ObjectDouble < BasicObject
end
class Shoulda::Matchers::Doublespeak::ProxyImplementation
  extend Forwardable
end
class Shoulda::Matchers::Doublespeak::StubImplementation
end
class Shoulda::Matchers::Doublespeak::World
end
class Shoulda::Matchers::Error < StandardError
end
class Shoulda::Matchers::MatcherContext
end
module Shoulda::Matchers::Independent
end
class Shoulda::Matchers::Independent::DelegateMethodMatcher
end
class Shoulda::Matchers::Independent::DelegateMethodMatcher::DelegateObjectNotSpecified < StandardError
end
module Shoulda::Matchers::Integrations
end
class Shoulda::Matchers::Integrations::Configuration
end
class Shoulda::Matchers::Integrations::ConfigurationError < StandardError
end
module Shoulda::Matchers::Integrations::Inclusion
end
module Shoulda::Matchers::Integrations::Rails
end
class Shoulda::Matchers::Integrations::Registry
end
module Shoulda::Matchers::Integrations::Libraries
end
class Shoulda::Matchers::Integrations::Libraries::ActionController
  include Shoulda::Matchers::Integrations::Inclusion
  include Shoulda::Matchers::Integrations::Rails
end
class Shoulda::Matchers::Integrations::Libraries::ActiveModel
  include Shoulda::Matchers::Integrations::Inclusion
  include Shoulda::Matchers::Integrations::Rails
end
class Shoulda::Matchers::Integrations::Libraries::ActiveRecord
  include Shoulda::Matchers::Integrations::Inclusion
  include Shoulda::Matchers::Integrations::Rails
end
class Shoulda::Matchers::Integrations::Libraries::MissingLibrary
end
class Shoulda::Matchers::Integrations::Libraries::Rails
  include Shoulda::Matchers::Integrations::Rails
end
class Shoulda::Matchers::Integrations::Libraries::Routing
  include Shoulda::Matchers::Integrations::Inclusion
  include Shoulda::Matchers::Integrations::Rails
end
module Shoulda::Matchers::Integrations::TestFrameworks
end
class Shoulda::Matchers::Integrations::TestFrameworks::ActiveSupportTestCase
end
class Shoulda::Matchers::Integrations::TestFrameworks::Minitest4
end
class Shoulda::Matchers::Integrations::TestFrameworks::Minitest5
end
class Shoulda::Matchers::Integrations::TestFrameworks::MissingTestFramework
end
class Shoulda::Matchers::Integrations::TestFrameworks::Rspec
end
class Shoulda::Matchers::Integrations::TestFrameworks::TestUnit
end
module Shoulda::Matchers::RailsShim
end
class InvalidName___Class_0x00___FakeAttributeType_74
end
module Shoulda::Matchers::WordWrap
end
class Shoulda::Matchers::Document
end
class Shoulda::Matchers::Text < String
end
class Shoulda::Matchers::Paragraph
end
class Shoulda::Matchers::Line
end
module Shoulda::Matchers::Util
end
module Shoulda::Matchers::ActionController
end
class Shoulda::Matchers::ActionController::FilterParamMatcher
end
class Shoulda::Matchers::ActionController::RouteParams
end
class Shoulda::Matchers::ActionController::SetFlashMatcher
  extend Forwardable
end
class Shoulda::Matchers::ActionController::SetFlashMatcher::QualifierOrderError < StandardError
end
class Shoulda::Matchers::ActionController::RenderWithLayoutMatcher
end
class Shoulda::Matchers::ActionController::RespondWithMatcher
end
class Shoulda::Matchers::ActionController::SetSessionMatcher
  extend Forwardable
end
class Shoulda::Matchers::ActionController::RouteMatcher
end
class Shoulda::Matchers::ActionController::RedirectToMatcher
end
class Shoulda::Matchers::ActionController::RenderTemplateMatcher
end
class Shoulda::Matchers::ActionController::RescueFromMatcher
end
class Shoulda::Matchers::ActionController::CallbackMatcher
end
class Shoulda::Matchers::ActionController::PermitMatcher
end
class Shoulda::Matchers::ActionController::PermitMatcher::CompositeParametersDoubleRegistry
end
class Shoulda::Matchers::ActionController::PermitMatcher::ParametersDoubleRegistry
end
class Shoulda::Matchers::ActionController::PermitMatcher::ActionNotDefinedError < StandardError
end
class Shoulda::Matchers::ActionController::PermitMatcher::VerbNotDefinedError < StandardError
end
class Shoulda::Matchers::ActionController::SetSessionOrFlashMatcher
end
class Shoulda::Matchers::ActionController::FlashStore
end
class Shoulda::Matchers::ActionController::SessionStore
end
module Shoulda::Matchers::ActiveModel
end
module Shoulda::Matchers::ActiveModel::Helpers
end
module Shoulda::Matchers::ActiveModel::Qualifiers
end
module Shoulda::Matchers::ActiveModel::Qualifiers::AllowNil
end
class Shoulda::Matchers::ActiveModel::Qualifiers::IgnoreInterferenceByWriter
end
module Shoulda::Matchers::ActiveModel::Qualifiers::IgnoringInterferenceByWriter
end
class Shoulda::Matchers::ActiveModel::ValidationMatcher
  include Shoulda::Matchers::ActiveModel::Qualifiers::IgnoringInterferenceByWriter
end
class Shoulda::Matchers::ActiveModel::ValidationMatcher::BuildDescription
end
class Shoulda::Matchers::ActiveModel::Validator
  include Shoulda::Matchers::ActiveModel::Helpers
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher
  include Shoulda::Matchers::ActiveModel::Helpers
  include Shoulda::Matchers::ActiveModel::Qualifiers::IgnoringInterferenceByWriter
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeChangedValueError < Shoulda::Matchers::Error
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeDoesNotExistError < Shoulda::Matchers::Error
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeSetter
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeSetterAndValidator
  extend Forwardable
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeSetters
  include Enumerable
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeSettersAndValidators
  include Enumerable
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::SuccessfulCheck
end
class Shoulda::Matchers::ActiveModel::AllowValueMatcher::SuccessfulSetting
end
class Shoulda::Matchers::ActiveModel::DisallowValueMatcher
  extend Forwardable
end
class Shoulda::Matchers::ActiveModel::ValidateLengthOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
  include Shoulda::Matchers::ActiveModel::Helpers
end
class Shoulda::Matchers::ActiveModel::ValidateInclusionOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
end
class Shoulda::Matchers::ActiveModel::ValidateExclusionOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
end
class Shoulda::Matchers::ActiveModel::ValidateAbsenceOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
end
class Shoulda::Matchers::ActiveModel::ValidatePresenceOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
  include Shoulda::Matchers::ActiveModel::Qualifiers::AllowNil
end
class Shoulda::Matchers::ActiveModel::ValidateAcceptanceOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
end
class Shoulda::Matchers::ActiveModel::ValidateConfirmationOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
  include Shoulda::Matchers::ActiveModel::Helpers
end
class Shoulda::Matchers::ActiveModel::ValidateNumericalityOfMatcher
  include Shoulda::Matchers::ActiveModel::Qualifiers::IgnoringInterferenceByWriter
end
module Shoulda::Matchers::ActiveModel::NumericalityMatchers
end
class Shoulda::Matchers::ActiveModel::NumericalityMatchers::NumericTypeMatcher
  extend Forwardable
end
class Shoulda::Matchers::ActiveModel::NumericalityMatchers::ComparisonMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
end
class Shoulda::Matchers::ActiveModel::NumericalityMatchers::OddNumberMatcher < Shoulda::Matchers::ActiveModel::NumericalityMatchers::NumericTypeMatcher
end
class Shoulda::Matchers::ActiveModel::NumericalityMatchers::EvenNumberMatcher < Shoulda::Matchers::ActiveModel::NumericalityMatchers::NumericTypeMatcher
end
class Shoulda::Matchers::ActiveModel::NumericalityMatchers::OnlyIntegerMatcher < Shoulda::Matchers::ActiveModel::NumericalityMatchers::NumericTypeMatcher
end
class Shoulda::Matchers::ActiveModel::CouldNotDetermineValueOutsideOfArray < RuntimeError
end
class Shoulda::Matchers::ActiveModel::NonNullableBooleanError < Shoulda::Matchers::Error
end
class Shoulda::Matchers::ActiveModel::CouldNotSetPasswordError < Shoulda::Matchers::Error
end
class Shoulda::Matchers::ActiveModel::HaveSecurePasswordMatcher
end
module Shoulda::Matchers::ActiveRecord
end
class Shoulda::Matchers::ActiveRecord::AssociationMatcher
end
module Shoulda::Matchers::ActiveRecord::AssociationMatchers
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::CounterCacheMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::InverseOfMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::JoinTableMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::OrderMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::ThroughMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::DependentMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::RequiredMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::OptionalMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::SourceMatcher
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::ModelReflector
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::ModelReflection < SimpleDelegator
end
class Shoulda::Matchers::ActiveRecord::AssociationMatchers::OptionVerifier
end
class Shoulda::Matchers::ActiveRecord::HaveDbColumnMatcher
end
class Shoulda::Matchers::ActiveRecord::HaveDbColumnMatcher::DecoratedColumn < SimpleDelegator
end
class Shoulda::Matchers::ActiveRecord::HaveDbIndexMatcher
end
class Shoulda::Matchers::ActiveRecord::HaveImplicitOrderColumnMatcher
end
class Shoulda::Matchers::ActiveRecord::HaveImplicitOrderColumnMatcher::SecondaryCheckFailedError < StandardError
end
class Shoulda::Matchers::ActiveRecord::HaveImplicitOrderColumnMatcher::PrimaryCheckFailedError < StandardError
end
class Shoulda::Matchers::ActiveRecord::HaveReadonlyAttributeMatcher
end
class Shoulda::Matchers::ActiveRecord::HaveRichTextMatcher
end
class Shoulda::Matchers::ActiveRecord::HaveSecureTokenMatcher
end
class Shoulda::Matchers::ActiveRecord::SerializeMatcher
end
class Shoulda::Matchers::ActiveRecord::AcceptNestedAttributesForMatcher
end
class Shoulda::Matchers::ActiveRecord::DefineEnumForMatcher
end
module Shoulda::Matchers::ActiveRecord::Uniqueness
end
class Shoulda::Matchers::ActiveRecord::Uniqueness::Model
end
class Shoulda::Matchers::ActiveRecord::Uniqueness::Namespace
end
class Shoulda::Matchers::ActiveRecord::Uniqueness::TestModelCreator
end
module Shoulda::Matchers::ActiveRecord::Uniqueness::TestModels
end
class Shoulda::Matchers::ActiveRecord::ValidateUniquenessOfMatcher < Shoulda::Matchers::ActiveModel::ValidationMatcher
  include Shoulda::Matchers::ActiveModel::Helpers
end
class Shoulda::Matchers::ActiveRecord::ValidateUniquenessOfMatcher::AttributeSetters
  include Enumerable
end
class Shoulda::Matchers::ActiveRecord::ValidateUniquenessOfMatcher::NonCaseSwappableValueError < Shoulda::Matchers::Error
end
class Shoulda::Matchers::ActiveRecord::ValidateUniquenessOfMatcher::ExistingRecordInvalid < Shoulda::Matchers::Error
  include Shoulda::Matchers::ActiveModel::Helpers
end
class Shoulda::Matchers::ActiveRecord::HaveAttachedMatcher
end
module Shoulda::Matchers::Routing
end
