# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/trailblazer-option/all/trailblazer-option.rbi
#
# trailblazer-option-0.1.2

module Trailblazer
end
class Trailblazer::Option
end
