# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/vcr/all/vcr.rbi
#
# vcr-6.1.0

module VCR
  extend VCR
  extend VCR
  include VCR::Errors
  include VCR::VariableArgsBlockCaller
end
class VCR::Logger
end
module VCR::Logger::Null
end
module VCR::Logger::Mixin
end
module VCR::VariableArgsBlockCaller
end
class VCR::Cassette
  include VCR::Logger::Mixin
end
class VCR::Cassette::HTTPInteractionList
  include VCR::Logger::Mixin
end
module VCR::Cassette::HTTPInteractionList::NullList
  extend VCR::Cassette::HTTPInteractionList::NullList
end
class VCR::Cassette::ERBRenderer
end
class VCR::Cassette::Serializers
end
module VCR::Cassette::EncodingErrorHandling
end
module VCR::Cassette::SyntaxErrorHandling
end
class VCR::Cassette::Persisters
end
module VCR::Errors
end
class VCR::Errors::Error < StandardError
end
class VCR::Errors::CassetteInUseError < VCR::Errors::Error
end
class VCR::Errors::TurnedOffError < VCR::Errors::Error
end
class VCR::Errors::MissingERBVariableError < VCR::Errors::Error
end
class VCR::Errors::LibraryVersionTooLowError < VCR::Errors::Error
end
class VCR::Errors::UnregisteredMatcherError < VCR::Errors::Error
end
class VCR::Errors::InvalidCassetteFormatError < VCR::Errors::Error
end
class VCR::Errors::AroundHTTPRequestHookError < VCR::Errors::Error
end
class VCR::Errors::NotSupportedError < VCR::Errors::Error
end
class VCR::Errors::UnknownContentEncodingError < VCR::Errors::Error
end
class VCR::Errors::UnusedHTTPInteractionError < VCR::Errors::Error
end
class VCR::Errors::EjectLinkedCassetteError < VCR::Errors::Error
end
class VCR::Errors::UnhandledHTTPRequestError < VCR::Errors::Error
end
class VCR::LinkedCassette < SimpleDelegator
end
class VCR::LinkedCassette::CassetteList
  include Enumerable
end
module VCR::Hooks
  include VCR::VariableArgsBlockCaller
end
class VCR::Hooks::FilteredHook < Struct
  include VCR::VariableArgsBlockCaller
end
module VCR::Hooks::ClassMethods
end
class VCR::Configuration
  extend VCR::Hooks::ClassMethods
  include VCR::Configuration::DefinedHooks
  include VCR::Hooks
  include VCR::Logger::Mixin
  include VCR::VariableArgsBlockCaller
end
module VCR::Configuration::DefinedHooks
end
module VCR::Deprecations
end
module VCR::Deprecations::Middleware
end
module VCR::Deprecations::Middleware::Faraday
end
class VCR::LibraryHooks
end
class VCR::RequestIgnorer
  extend VCR::Hooks::ClassMethods
  include VCR::Hooks
  include VCR::RequestIgnorer::DefinedHooks
end
module VCR::RequestIgnorer::DefinedHooks
end
class VCR::RequestMatcherRegistry
end
class VCR::RequestMatcherRegistry::Matcher < Anonymous_Struct_75
end
class VCR::RequestMatcherRegistry::URIWithoutParamsMatcher < Anonymous_Struct_76
end
module VCR::Normalizers
end
module VCR::Normalizers::Body
end
module VCR::Normalizers::Body::ClassMethods
end
module VCR::Normalizers::Header
end
class VCR::Request < Anonymous_Struct_77
  extend VCR::Normalizers::Body::ClassMethods
  include VCR::Normalizers::Body
  include VCR::Normalizers::Header
end
class VCR::Request::Typed < Anonymous_Delegator_78
end
class VCR::Request::FiberAware < Anonymous_Delegator_79
end
class VCR::Response < Anonymous_Struct_80
  extend VCR::Normalizers::Body::ClassMethods
  include VCR::Normalizers::Body
  include VCR::Normalizers::Header
end
class VCR::ResponseStatus < Anonymous_Struct_81
end
class VCR::HTTPInteraction < Anonymous_Struct_82
end
class VCR::HTTPInteraction::HookAware < Anonymous_Delegator_83
end
module VCR::RSpec
end
module VCR::Middleware
end
module VCR::Cassette::Persisters::FileSystem
  extend VCR::Cassette::Persisters::FileSystem
end
class VCR::VersionChecker
end
class VCR::RequestHandler
  include VCR::Logger::Mixin
end
module VCR::LibraryHooks::WebMock
  extend VCR::LibraryHooks::WebMock
  extend VCR::LibraryHooks::WebMock::Helpers
end
module VCR::LibraryHooks::WebMock::Helpers
end
class VCR::LibraryHooks::WebMock::RequestHandler < VCR::RequestHandler
  include VCR::LibraryHooks::WebMock::Helpers
end
module WebMock
end
