# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/vite_rails/all/vite_rails.rbi
#
# vite_rails-3.0.9

module ViteRails
end
module ViteRails::Config
  def config_defaults; end
end
module ViteRails::TagHelpers
  def vite_asset_path(name, **options); end
  def vite_asset_url(name, **options); end
  def vite_client_tag; end
  def vite_image_tag(name, **options); end
  def vite_javascript_tag(*names, type: nil, asset_type: nil, skip_preload_tags: nil, skip_style_tags: nil, crossorigin: nil, media: nil, **options); end
  def vite_manifest; end
  def vite_preload_tag(*sources, crossorigin:, **options); end
  def vite_react_refresh_tag; end
  def vite_stylesheet_tag(*names, **options); end
  def vite_typescript_tag(*names, **options); end
end
class ViteRails::Engine < Rails::Engine
end
