// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('add-group', true, (props: ISvgIconProps) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4.33333 4C4.14924 4 4 4.14924 4 4.33333V17.6667C4 17.8508 4.14924 18 4.33333 18H6.5V20H4.33333C3.04467 20 2 18.9553 2 17.6667V4.33333C2 3.04467 3.04467 2 4.33333 2H17.6667C18.9553 2 20 3.04467 20 4.33333V7H18V4.33333C18 4.14924 17.8508 4 17.6667 4H4.33333Z"
      fill="currentColor"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8.16667 8C8.07462 8 8 8.07462 8 8.16667V19.8333C8 19.9254 8.07462 20 8.16667 20H19.8333C19.9254 20 20 19.9254 20 19.8333V8.16667C20 8.07462 19.9254 8 19.8333 8H8.16667ZM6 8.16667C6 6.97005 6.97005 6 8.16667 6H19.8333C21.03 6 22 6.97005 22 8.16667V19.8333C22 21.03 21.03 22 19.8333 22H8.16667C6.97005 22 6 21.03 6 19.8333V8.16667Z"
      fill="currentColor"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14 10C14.5523 10 15 10.4477 15 11V17C15 17.5523 14.5523 18 14 18C13.4477 18 13 17.5523 13 17V11C13 10.4477 13.4477 10 14 10Z"
      fill="currentColor"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10 14C10 13.4477 10.4477 13 11 13H17C17.5523 13 18 13.4477 18 14C18 14.5523 17.5523 15 17 15H11C10.4477 15 10 14.5523 10 14Z"
      fill="currentColor"
    />
  </svg>
))
