// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file AlignRight edit/align-right.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'align-right',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M3 5.9749C3 5.42261 3.44772 4.9749 4 4.9749H20C20.5523 4.9749 21 5.42261 21 5.9749C21 6.52718 20.5523 6.9749 20 6.9749H4C3.44772 6.9749 3 6.52718 3 5.9749Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M8 11.9749C8 11.4226 8.44772 10.9749 9 10.9749H20C20.5523 10.9749 21 11.4226 21 11.9749C21 12.5272 20.5523 12.9749 20 12.9749H9C8.44772 12.9749 8 12.5272 8 11.9749Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2.97488 17.9749C2.97488 17.4226 3.4226 16.9749 3.97488 16.9749H19.9749C20.5272 16.9749 20.9749 17.4226 20.9749 17.9749C20.9749 18.5272 20.5272 18.9749 19.9749 18.9749H3.97488C3.4226 18.9749 2.97488 18.5272 2.97488 17.9749Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
