// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file AlignCenter edit/align-center.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'align-center',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2.97488 5.9749C2.97488 5.42261 3.4226 4.9749 3.97488 4.9749H19.9749C20.5272 4.9749 20.9749 5.42261 20.9749 5.9749C20.9749 6.52718 20.5272 6.9749 19.9749 6.9749H3.97488C3.4226 6.9749 2.97488 6.52718 2.97488 5.9749Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M5 11.9749C5 11.4226 5.44772 10.9749 6 10.9749H17C17.5523 10.9749 18 11.4226 18 11.9749C18 12.5272 17.5523 12.9749 17 12.9749H6C5.44772 12.9749 5 12.5272 5 11.9749Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2.97488 17.9749C2.97488 17.4226 3.4226 16.9749 3.97488 16.9749H19.9749C20.5272 16.9749 20.9749 17.4226 20.9749 17.9749C20.9749 18.5272 20.5272 18.9749 19.9749 18.9749H3.97488C3.4226 18.9749 2.97488 18.5272 2.97488 17.9749Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
