// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file Alipay platform/alipay.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('alipay', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path
      fill={props.colors[0]}
      d="M12 0c6.627 0 12 5.373 12 12s-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0zm0 2.182c-5.422 0-9.818 4.396-9.818 9.818S6.578 21.818 12 21.818a9.808 9.808 0 0 0 8.11-4.282 32.012 32.012 0 0 1-3.341-1.202c-.619-.26-1.542-.67-2.771-1.229C12.528 16.587 10.384 18 8.088 18c-1.595-.008-4.27-.814-4.27-3.327 0-2.514 2.478-3.112 4.086-3.112.973 0 2.695.537 5.165 1.611l.038.015a6.816 6.816 0 0 0 1.366-2.827l.05-.231H8.087v-1.16h2.929v-1.45h-4.1v-.87h4.1v-1.74h2.344v1.74h4.687v.87H13.36v1.45h3.743c-.055.362-.117.69-.186.986l-.042.173c-.172.623-.56 1.53-1.162 2.721-.16.317-.391.682-.683 1.07.922.342 1.856.673 2.8.995 1.223.416 2.28.753 3.173 1.01A9.784 9.784 0 0 0 21.818 12c0-5.422-4.396-9.818-9.818-9.818zm-6.842 12.09c0 1.599 3.344 2.236 6.054.553.305-.19.59-.392.855-.607l-.009-.004-.213-.13c-1.691-1.03-3.005-1.587-3.941-1.674-.86-.08-2.746.263-2.746 1.862zm9.365-4.144h1.104-1.104z"
    />
  </svg>
))
