// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file AppStore platform/app-store.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('app-store', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M19.5 3h-15A1.5 1.5 0 0 0 3 4.5v15A1.5 1.5 0 0 0 4.5 21h15a1.5 1.5 0 0 0 1.5-1.5v-15A1.5 1.5 0 0 0 19.5 3z"
    />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M14 6.5 10.75 12l-.813 1.375-.406.688M7.5 17.5l.406-.688M6 14.5h5.5m3.5 0h3m-8.5-8 1.75 2.75.438.688M16.5 17.5l-1.75-2.75-.875-1.375-.438-.688"
    />
  </svg>
))
