// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file ArrowCircleUp basic/arrow-circle-up.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('arrow-circle-up', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path
      strokeLinejoin="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"
    />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke={props.colors[0]} d="M12 17.5v-9M7.5 11.5 12 7l4.5 4.5" />
  </svg>
))
