// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('arrow-circle-left', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path
      strokeLinejoin="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"
    />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="M16.246 12.25h-9M11.746 7.75l-4.5 4.5 4.5 4.5" />
  </svg>
))
