// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('bring-forward', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill="#fff" d="M24 0H0v24h24V0z" />
    <path strokeLinejoin="round" strokeWidth="2" stroke="#3E3E3E" d="M21 17H3v4h18v-4zM21 10H3v4h18v-4z" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="m15 6-3-3-3 3M12 14v3M12 3v7" />
  </svg>
))
