// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file BringForward rich-text/bring-forward.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('bring-forward', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path strokeLinejoin="round" strokeWidth="2" stroke={props.colors[0]} d="M21 17H3v4h18v-4zM21 10H3v4h18v-4z" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke={props.colors[0]} d="m15 6-3-3-3 3M12 14v3M12 3v7" />
  </svg>
))
