// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('bug', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill="#fff" d="M24 0H0v24h24V0z" />
    <path strokeLinejoin="round" strokeWidth="2" stroke="#3E3E3E" d="M12 21c6 0 7-5.234 7-7V7H5v7c0 1.725 1 7 7 7z" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="m2 4 3 3M22 4l-3 3M2 13.5h3M22 13.5h-3M3.5 22l3-3M20.5 22l-3-3M12 21V7M7.46 19.52C8.501 20.392 9.962 21 12 21c2.056 0 3.524-.614 4.567-1.493"
    />
    <path strokeLinejoin="round" strokeWidth="2" stroke="#3E3E3E" d="M16 6.167C16 3.865 14.21 2 12 2S8 3.865 8 6.167V7h8v-.833z" />
  </svg>
))
