// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('calendar', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill="#fff" d="M24 0H0v24h24V0z" />
    <path
      strokeLinejoin="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="M2.5 9.5h19V20a1 1 0 0 1-1 1h-17a1 1 0 0 1-1-1V9.5zM2.5 4.5a1 1 0 0 1 1-1h17a1 1 0 0 1 1 1v5h-19v-5z"
    />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="M8 2v4M16 2v4M14 17h3M7 17h3M14 13h3M7 13h3" />
  </svg>
))
