// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('certificate', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="M13 18H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-4M6 7h12M6 10.5h3M6 14h2"
    />
    <path strokeWidth="2" stroke="#3E3E3E" d="M15 16.5a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="m15 20 2 1v-5.264s-.57.764-2 .764c-1.43 0-2-.75-2-.75V21l2-1z"
    />
  </svg>
))
