// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Change basic/change.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('change', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path
      fill={props.colors[0]}
      d="M1.707 4.707A1 1 0 0 1 .293 3.293l3-3a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1-1.414 1.414L4 2.414 1.707 4.707zm4.586 4.586a1 1 0 0 1 1.414 1.414l-3 3a1 1 0 0 1-1.414 0l-3-3a1 1 0 1 1 1.414-1.414L4 11.586l2.293-2.293z"
    />
  </svg>
))
