// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file CheckOne basic/check-one.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'check-one',
    false,
    (props: ISvgIconProps) => (
        <svg
            fill="none"
            viewBox="0 0 24 24"
        >
            <path
                fillOpacity=".01"
                fill={props.colors[2]}
                d="M24 0H0v24h24V0z"
            />
            <path
                strokeLinejoin="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="M12 22a9.97 9.97 0 0 0 7.071-2.929A9.97 9.97 0 0 0 22 12a9.969 9.969 0 0 0-2.929-7.071A9.969 9.969 0 0 0 12 2a9.969 9.969 0 0 0-7.071 2.929A9.969 9.969 0 0 0 2 12a9.969 9.969 0 0 0 2.929 7.071A9.969 9.969 0 0 0 12 22z"
            />
            <path
                strokeLinejoin="round"
                strokeLinecap="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="m8 12 3 3 6-6"
            />
        </svg>
    )
);
