// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file CheckBox basic/check-box.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'check-box',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M18.2233 6.75377C18.7226 7.15326 18.8036 7.88191 18.4041 8.38126L11.4568 17.0654C11.251 17.3226 10.9455 17.48 10.6166 17.4982C10.2878 17.5164 9.96674 17.3937 9.73386 17.1609L5.68124 13.1082C5.22906 12.6561 5.22906 11.9229 5.68124 11.4707C6.13342 11.0186 6.86656 11.0186 7.31874 11.4707L10.4566 14.6086L16.5958 6.9346C16.9953 6.43525 17.7239 6.35429 18.2233 6.75377Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
