// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Code edit/code.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('code', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" width={props.size} height={props.size} fill="none">
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M7.694 6.28a1 1 0 0 1 .026 1.414l-4.306 4.46 4.28 4.126a1 1 0 0 1-1.388 1.44l-5-4.82a1 1 0 0 1-.026-1.414l5-5.18a1 1 0 0 1 1.414-.026ZM16.305 6.28a1 1 0 0 1 1.415.026l5 5.18a1 1 0 0 1-.026 1.414l-5 4.82a1 1 0 0 1-1.388-1.44l4.28-4.125-4.305-4.46a1 1 0 0 1 .024-1.415ZM14.217 2.024a1 1 0 0 1 .76 1.193l-4 18a1 1 0 1 1-1.953-.434l4-18a1 1 0 0 1 1.193-.76Z"
      fill={props.colors[0]}
    />
  </svg>
))
