// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('code', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="m8 6.5-6 6.216L8 18.5M16 6.5l6 6.216-6 5.784" />
    <path strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="m14 2-3.5 20" />
  </svg>
))
