// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file ColorCard basic/color-card.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('color-card', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="m8 11.757 9.507-9.507.236-.25 4.25 4.25-9.75 9.75M5 22a3 3 0 0 0 3-3v-7.243L5 22zm0 0a3 3 0 0 1-3-3V2h6v9.757L5 22zm0 0h17v-6h-9.757L5 22zm-2.121-.879a3 3 0 0 0 4.242 0L12.243 16l-9.364 5.121z"
    />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M7.121 21.121 21.993 6.25 17.743 2 8 11.757M12.243 16H22v6H6.25"
    />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke={props.colors[0]} d="M12.243 16H22v6H6.25" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M5 22a3 3 0 0 0 3-3V2H2v17a3 3 0 0 0 3 3z"
    />
  </svg>
))
