// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Delete basic/delete.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('delete', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path
      fill={props.colors[0]}
      d="M4 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v17a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5zm2 1v15h12V6H6z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
    <path
      fill={props.colors[0]}
      d="M10 9a1 1 0 0 1 1 1v6.5a1 1 0 1 1-2 0V10a1 1 0 0 1 1-1zm4 0a1 1 0 0 1 1 1v6.5a1 1 0 1 1-2 0V10a1 1 0 0 1 1-1zM1 5a1 1 0 0 1 1-1h20a1 1 0 1 1 0 2H2a1 1 0 0 1-1-1z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
    <path
      fill={props.colors[0]}
      d="M8.768 1.52A1 1 0 0 1 9.645 1h4.744a1 1 0 0 1 .88.527l1.612 3A1 1 0 0 1 16 6H8a1 1 0 0 1-.877-1.48l1.645-3zM10.237 3l-.548 1h4.639l-.537-1h-3.554z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
  </svg>
))
