// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file DividingLine rich-text/dividing-line.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'dividing-line',
    false,
    (props: ISvgIconProps) => (
        <svg
            fill="none"
            viewBox="0 0 24 24"
        >
            <path
                strokeLinejoin="round"
                strokeLinecap="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="M2.5 12h19M10.5 19h3M18.5 19h3M10.5 5h3M2.5 19h3M2.5 5h3M18.5 5h3"
            />
        </svg>
    )
);
