// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file DoubleDown basic/double-down.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('double-down', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="m18 6-6 6-6-6m12 6-6 6-6-6"
    />
  </svg>
))
