// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('double-down', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="m18 6-6 6-6-6M18 12l-6 6-6-6" />
  </svg>
))
