// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file Face basic/face.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('face', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24">
    <path
      fill="currentColor"
      d="M1 12C1 5.925 5.925 1 12 1s11 4.925 11 11-4.925 11-11 11S1 18.075 1 12zm11-9a9 9 0 1 0 0 18 9 9 0 0 0 0-18z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M8.458 13.275a.889.889 0 0 1 1.208.346 2.666 2.666 0 0 0 4.668 0 .889.889 0 0 1 1.554.863 4.443 4.443 0 0 1-7.776 0 .889.889 0 0 1 .346-1.209zM9.5 11a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zM14.5 11a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
  </svg>
))
