// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file FilePdf file/file-pdf.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('file-pdf', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path strokeLinejoin="round" strokeWidth="2" stroke="currentColor" d="M5 2h10l5 5v14a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="currentColor"
      d="M9 9h6v3.996L9.004 13 9 9z"
      clipRule="evenodd"
    />
    <path strokeLinecap="round" strokeWidth="2" stroke="currentColor" d="M9 9v8" />
  </svg>
))
