// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('filter', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path strokeLinejoin="round" strokeWidth="2" stroke="#3E3E3E" d="m3 4.5 7.2 8.409v6.313L13.8 21v-8.091L21 4.5H3z" />
  </svg>
))
