// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Filter basic/filter.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'filter',
    false,
    (props: ISvgIconProps) => (
        <svg
            viewBox="0 0 24 24"
            width={props.size}
            height={props.size}
            fill="none"
        >
            <path
                strokeLinejoin="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="m3 4.5 7.2 8.409v6.313L13.8 21v-8.091L21 4.5H3z"
            />
        </svg>
    )
);
