// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file HamburgerButton basic/hamburger-button.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('hamburger-button', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24">
    <path d="M24 0H0v24h24V0z" fill={props.colors[2]} fillOpacity=".01" />
    <path
      d="M3.975 5.975h16m-16 6h16m-16 6h16"
      stroke={props.colors[0]}
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
))
