// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('image', true, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 4a1 1 0 0 1 1-1h20a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4zm2 1v14h18V5H3z"
      fill="currentColor"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16.31 8.777a1 1 0 0 1 1.359-.02l5 4.5-1.338 1.486-4.311-3.88-10.33 9.86-1.38-1.446 11-10.5z"
      fill="currentColor"
    />
    <path d="M9 9a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" fill="currentColor" />
  </svg>
))
