// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('inbox', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill="#fff" d="M24 0H0v24h24V0z" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="M2 15 4.5 3h15L22 15" />
    <path strokeLinejoin="round" strokeWidth="2" stroke="#3E3E3E" d="M2 15h5.455l.909 3h7.272l.91-3H22v6.5H2V15z" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#3E3E3E" d="M9.5 7h5M8 11h8" />
  </svg>
))
