// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file ListUnordered rich-text/list-unordered.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'list-unordered',
    false,
    (props: ISvgIconProps) => (
        <svg
            fill="none"
            viewBox="0 0 24 24"
        >
            <path
                fill="currentColor"
                d="M6 4a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm0 16a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm-2-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm5-3a1 1 0 1 0 0 2h12a1 1 0 1 0 0-2H9zm-1 9a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H9a1 1 0 0 1-1-1zM9 3a1 1 0 0 0 0 2h12a1 1 0 1 0 0-2H9z"
                clipRule="evenodd"
                fillRule="evenodd"
            />
        </svg>
    )
);
