// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file Mail basic/mail.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('mail', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path strokeLinejoin="round" strokeWidth="2" stroke="#333" d="M2 19.5h20v-15H2v15z" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#333" d="M2 4.5 12 12l10-7.5" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#333" d="M12 4.5H2V12M22 12V4.5H12" />
  </svg>
))
