// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Me basic/me.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('me', false, (props: ISvgIconProps) => (
  <svg width={props.size} height={props.size} viewBox="0 0 24 24" fill="none">
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12ZM12 3C7.02943 3 3 7.02943 3 12C3 16.9706 7.02943 21 12 21C16.9706 21 21 16.9706 21 12C21 7.02943 16.9706 3 12 3Z"
      fill={props.colors[0]}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8.5 9C8.5 7.06702 10.067 5.5 12 5.5C13.933 5.5 15.5 7.06702 15.5 9C15.5 10.933 13.933 12.5 12 12.5C10.067 12.5 8.5 10.933 8.5 9ZM12 7.5C11.1716 7.5 10.5 8.17158 10.5 9C10.5 9.82841 11.1716 10.5 12 10.5C12.8284 10.5 13.5 9.82841 13.5 9C13.5 8.17158 12.8284 7.5 12 7.5Z"
      fill={props.colors[0]}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.99999 15.5C7.88103 15.5 6.14624 17.1482 6.00883 19.2318C5.97248 19.7829 5.49627 20.2002 4.94518 20.1638C4.3941 20.1275 3.97682 19.6513 4.01316 19.1002C4.21944 15.9724 6.82055 13.5 9.99999 13.5H14C17.1752 13.5 19.7737 15.9658 19.986 19.0878C20.0235 19.6388 19.6072 20.1159 19.0562 20.1533C18.5052 20.1908 18.0281 19.7745 17.9906 19.2235C17.8492 17.1438 16.1162 15.5 14 15.5H9.99999Z"
      fill={props.colors[0]}
    />
  </svg>
))
