// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file MenuFold basic/menu-fold.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('menu-fold', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M4 5.5h16M4 12h16M4 18.5h16M6.828 14.829 4 12l2.828-2.828"
    />
  </svg>
))
