// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file MergeCells rich-text/merge-cells.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('merge-cells', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M10 7V2.5a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0-.5.5v19a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V17m4 0v4.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5v-19a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0-.5.5V7m0 5h8M2.5 12H10"
    />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="m16.374 14.41-.795-.796-1.591-1.591 1.59-1.591.796-.796M7.688 14.41l.795-.796 1.591-1.591-1.591-1.591-.796-.796"
    />
  </svg>
))
