// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Message basic/message.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('message', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#333" d="M2 3h20v15h-7.5L12 20.5 9.5 18H2V3z" />
    <path strokeLinecap="round" strokeWidth="2" stroke="#333" d="M11.5 10.5h1.001M16.5 10.5h1M6.5 10.5h1" />
  </svg>
))
