// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('pic', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="M19.5 3h-15A1.5 1.5 0 0 0 3 4.5v15A1.5 1.5 0 0 0 4.5 21h15a1.5 1.5 0 0 0 1.5-1.5v-15A1.5 1.5 0 0 0 19.5 3z"
    />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="M9 11.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5zM13.895 13.11a1 1 0 0 1 1.621.026l4.388 6.292a1 1 0 0 1-.82 1.572H8l5.895-7.89z"
    />
  </svg>
))
