// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Pin basic/pin.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('pin', false, (props: ISvgIconProps) => (
  <svg width={props.size} height={props.size} viewBox="0 0 24 24" fill="none">
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17.9301 13.0203C17.4192 12.3677 17.1426 11.5701 17.1429 10.75V4.5H18.4286C19.1357 4.5 19.7143 3.9375 19.7143 3.25C19.7143 2.5625 19.1357 2 18.4286 2H5.57143C4.86429 2 4.28571 2.5625 4.28571 3.25C4.28571 3.9375 4.86429 4.5 5.57143 4.5H6.85714V10.75C6.85714 12.475 5.66143 13.925 4.02857 14.3625C3.43714 14.525 3 15 3 15.5875V15.75C3 16.4375 3.57857 17 4.28571 17H11V21H10C9.44772 21 9 21.4477 9 22C9 22.5523 9.44772 23 10 23H14C14.5523 23 15 22.5523 15 22C15 21.4477 14.5523 21 14 21H13V17H19.7143C20.4214 17 21 16.4375 21 15.75V15.5875C21 15 20.5629 14.525 19.9714 14.3625C19.1582 14.1444 18.4411 13.6729 17.9301 13.0203ZM8.85714 4H15.1429V10.7494C15.1426 12.0216 15.5721 13.2528 16.3554 14.2533C16.5673 14.5238 16.8017 14.7734 17.0552 15H6.94295C8.11177 13.9571 8.85714 12.4511 8.85714 10.75V4Z"
      fill="currentColor"
    />
  </svg>
))
