// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file Point rich-text/point.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('point', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <circle fill={props.colors[0]} r="3" cy="12" cx="12" />
  </svg>
))
