// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Preview basic/preview.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('preview', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" width={props.size} height={props.size} fill="none">
    <path
      d="M19.5 5h-15C3.672 5 3 5.756 3 6.688v5.625C3 13.244 3.672 14 4.5 14h15c.828 0 1.5-.755 1.5-1.688V6.689C21 5.755 20.328 5 19.5 5ZM3 18h18"
      stroke={props.colors[0]}
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
))
