// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Quote rich-text/quote.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('quote', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path
      fill={props.colors[0]}
      d="M9.427 4.558C5.66 6.976 3.57 9.791 3.15 13.001 2.5 18 6.97 20.447 9.234 18.248c2.265-2.198.907-4.988-.733-5.75-1.64-.764-2.643-.498-2.468-1.517.175-1.02 2.509-3.845 4.558-5.161a.374.374 0 0 0 .057-.51l-.507-.66c-.22-.286-.43-.275-.715-.092zm9.913 0c-3.766 2.418-5.858 5.233-6.276 8.443-.651 4.999 3.82 7.446 6.084 5.247 2.265-2.198.907-4.988-.733-5.75-1.64-.764-2.643-.498-2.468-1.517.175-1.02 2.508-3.845 4.558-5.161a.374.374 0 0 0 .057-.51l-.507-.66c-.22-.286-.43-.275-.715-.092z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
  </svg>
))
