// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file RemoveAnchorMark basic/remove-anchor-mark.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'remove-anchor-mark',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                d="M11 14.8184V20.9451C6.82838 20.4839 3.51608 17.1716 3.05493 13H5C5.55228 13 6 12.5523 6 12C6 11.4477 5.55228 11 5 11H2C1.44772 11 1 11.4477 1 12C1 18.0751 5.92487 23 12 23C14.0584 23 15.9848 22.4346 17.6323 21.4506L16.163 19.9814C15.1982 20.4856 14.1307 20.8201 13 20.9451V16.8184L11 14.8184Z"
                fill="currentColor"
            />
            <path
                d="M19.9814 16.163L21.4506 17.6323C22.4346 15.9848 23 14.0584 23 12C23 11.4477 22.5523 11 22 11H19C18.4477 11 18 11.4477 18 12C18 12.5523 18.4477 13 19 13H20.9451C20.8201 14.1307 20.4856 15.1982 19.9814 16.163Z"
                fill="currentColor"
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M13 9.18162L8.50488 4.68651C8.50164 4.62475 8.5 4.56257 8.5 4.5C8.5 2.567 10.067 1 12 1C13.933 1 15.5 2.567 15.5 4.5C15.5 6.0855 14.4457 7.42478 13 7.85506V9.18162ZM13.5 4.5C13.5 5.32841 12.8284 6 12 6C11.1716 6 10.5 5.32841 10.5 4.5C10.5 3.67158 11.1716 3 12 3C12.8284 3 13.5 3.67158 13.5 4.5Z"
                fill="currentColor"
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2.29289 2.29289C2.68342 1.90237 3.31658 1.90237 3.70711 2.29289L21.7071 20.2929C22.0976 20.6834 22.0976 21.3166 21.7071 21.7071C21.3166 22.0976 20.6834 22.0976 20.2929 21.7071L2.29289 3.70711C1.90237 3.31658 1.90237 2.68342 2.29289 2.29289Z"
                fill="currentColor"
            />
        </svg>
    )
);
