// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('rotation', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill="#fff" d="M24 0H0v24h24V0z" />
    <path strokeLinejoin="round" strokeLinecap="round" strokeWidth="2" stroke="#333" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2" />
    <path
      strokeDasharray="1 3"
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#333"
      d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2"
    />
  </svg>
))
