// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Row rich-text/row.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'row',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M1 4C1 2.89543 1.89543 2 3 2H21C22.1046 2 23 2.89543 23 4V20C23 21.1046 22.1046 22 21 22H3C1.89543 22 1 21.1046 1 20V4ZM21 4H3V20H21V4Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2 9C2 8.44772 2.42736 8 2.95455 8H22.0455C22.5726 8 23 8.44772 23 9C23 9.55228 22.5726 10 22.0455 10H2.95455C2.42736 10 2 9.55228 2 9Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2 15C2 14.4477 2.42736 14 2.95455 14H22.0455C22.5726 14 23 14.4477 23 15C23 15.5523 22.5726 16 22.0455 16H2.95455C2.42736 16 2 15.5523 2 15Z"
                fill={props.colors[0]}
            />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2 3C2.55228 3 3 3.44772 3 4V20H21V4C21 3.44772 21.4477 3 22 3C22.5523 3 23 3.44772 23 4V20C23 21.1046 22.1046 22 21 22H3C1.89543 22 1 21.1046 1 20V4C1 3.44772 1.44772 3 2 3Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
