// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('rte-h2', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path
      fill="currentColor"
      d="M20.682 16.848c.295-.353.431-.707.431-1.07 0-.385-.098-.607-.237-.74-.146-.14-.4-.241-.8-.241-.396 0-.643.133-.809.368l-.004.006-.004.005c-.189.25-.31.641-.33 1.261l-.011.365h-1.88l.005-.383c.012-.976.28-1.798.834-2.424.572-.679 1.34-.995 2.241-.995.8 0 1.504.238 2.056.766l.003.003c.538.528.812 1.208.812 2.02 0 .811-.3 1.533-.844 2.168l-.008.01c-.328.358-.881.807-1.646 1.352l-.003.002a6.507 6.507 0 0 0-1 .837H23V22h-6v-.378c0-.893.277-1.683.85-2.364.315-.395.932-.906 1.794-1.535.51-.38.848-.667 1.038-.875z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
    <path fill="currentColor" d="M1 2v20h2.578v-8.964h8.844V22H15V2h-2.578v8.431H3.578V2H1z" />
  </svg>
))
