// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file RteH1 edit/rte-h1.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('rte-h1', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" width={props.size} height={props.size} fill="none">
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M20.407 13H22v9h-2.159v-6.113a5.331 5.331 0 0 1-1.244.53L18 16.59v-2.211l.354-.09a4.204 4.204 0 0 0 1.012-.424 4.19 4.19 0 0 0 .902-.714l.139-.151Z"
      fill={props.colors[0]}
    />
    <path d="M2 2v20h2.578v-8.964h8.844V22H16V2h-2.578v8.431H4.578V2H2Z" fill={props.colors[0]} />
  </svg>
))
