// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file RteH2 edit/rte-h2.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'rte-h2',
    false,
    (props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M20.6817 16.8479C20.9774 16.4953 21.1134 16.1411 21.1134 15.7785C21.1134 15.3935 21.0145 15.1712 20.8761 15.0386C20.73 14.8984 20.4765 14.797 20.0752 14.797C19.6803 14.797 19.4331 14.9296 19.2672 15.1654L19.2633 15.1709L19.2593 15.1763C19.0705 15.4251 18.9496 15.8174 18.9294 16.4371L18.9175 16.8016H17.0385L17.043 16.4194C17.0546 15.4425 17.3227 14.6214 17.8773 13.9954C18.4491 13.3162 19.2175 13 20.1181 13C20.9179 13 21.6223 13.2375 22.174 13.7664L22.177 13.7693C22.7152 14.2972 22.9893 14.9767 22.9893 15.7898C22.9893 16.6004 22.6884 17.3217 22.1453 17.9567L22.1372 17.9662C21.8087 18.325 21.2556 18.7736 20.4905 19.319L20.4877 19.321C20.0857 19.6018 19.7751 19.8589 19.5496 20.0916C19.5278 20.114 19.507 20.1361 19.4872 20.1577H23V22H17V21.6225C17 20.7289 17.2773 19.9385 17.8496 19.2578C18.1649 18.8632 18.7819 18.3519 19.6444 17.723C20.1538 17.3424 20.4922 17.0564 20.6817 16.8479Z"
                fill={props.colors[0]}
            />
            <path
                d="M1 2V22H3.5777V13.0364H12.4223V22H15V2H12.4223V10.4314H3.5777V2H1Z"
                fill={props.colors[0]}
            />
        </svg>
    )
);
