// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file RteH5 edit/rte-h5.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('rte-h5', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" width={props.size} height={props.size} fill="none">
    <path d="M1 2v20h2.578v-8.964h8.844V22H15V2h-2.578v8.431H3.578V2H1Z" fill={props.colors[0]} />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M23.628 11.754h-6.567l-.594 6.128h1.948l.071-.128c.172-.306.4-.522.702-.667l.004-.001c.262-.132.599-.198 1.008-.198.598 0 1.02.168 1.294.487l.003.003c.286.321.455.789.455 1.416 0 .552-.185.973-.52 1.285-.356.318-.798.481-1.33.481-.51 0-.887-.118-1.14-.302-.296-.215-.48-.551-.544-1.048l-.028-.218h-2.1l.02.269c.076.992.501 1.801 1.29 2.393.691.526 1.53.792 2.488.792 1.048 0 1.958-.312 2.733-.938l.004-.002c.84-.706 1.265-1.617 1.265-2.726 0-1.127-.323-2.048-.965-2.72-.64-.672-1.479-1.002-2.477-1.002a3.62 3.62 0 0 0-1.304.225c-.257.09-.494.21-.713.36l.199-1.947h4.798v-1.942Z"
      fill={props.colors[0]}
    />
  </svg>
))
