// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('save', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path
      strokeLinejoin="round"
      strokeWidth="2"
      stroke="#333"
      d="M19.65 3H4.35A1.35 1.35 0 0 0 3 4.35v15.3c0 .746.604 1.35 1.35 1.35h15.3A1.35 1.35 0 0 0 21 19.65V4.35A1.35 1.35 0 0 0 19.65 3z"
    />
    <path strokeLinejoin="round" strokeWidth="2" stroke="#333" d="M16 3v9H7.5V3H16z" />
    <path strokeLinecap="round" strokeWidth="2" stroke="#333" d="M13 6.5v2M5.498 3H18" />
  </svg>
))
