// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('search', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path
      fill="#3E3E3E"
      d="M10.5 1a9.5 9.5 0 1 0 5.973 16.887l3.673 3.674a1 1 0 0 0 1.415-1.415l-3.674-3.673A9.46 9.46 0 0 0 20 10.5 9.5 9.5 0 0 0 10.5 1zM3 10.5a7.5 7.5 0 1 1 15 0 7.5 7.5 0 0 1-15 0z"
      clipRule="evenodd"
      fillRule="evenodd"
    />
  </svg>
))
