// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('setting-config', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill="#fff" d="M24 0H0v24h24V0z" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#333"
      d="M20.75 5h-3M13.75 3v4M13.75 5h-11M6.75 12h-4M10.75 10v4M21.75 12h-11M20.75 19h-3M13.75 17v4M13.75 19h-11"
    />
  </svg>
))
