// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file Shield basic/shield.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('shield', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path
      strokeLinejoin="round"
      strokeWidth="2"
      stroke="#333"
      d="M3 4.128 12.004 1.5 21 4.128v5.389A13.158 13.158 0 0 1 12.001 22 13.16 13.16 0 0 1 3 9.514V4.128z"
    />
  </svg>
))
