// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Sort basic/sort.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'sort',
    false,
    (props: ISvgIconProps) => (
        <svg
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                strokeLinejoin="round"
                strokeLinecap="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="M12.5 7 8 2.5 3.5 7m4.496 8.5v-13M21 17l-4.5 4.5L12 17m4.496-8.5v13"
            />
        </svg>
    )
);
