// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Success basic/success.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'success',
    false,
    (props: ISvgIconProps) => (
        <svg
            viewBox="0 0 24 24"
            fill="none"
        >
            <path
                fillOpacity=".01"
                fill={props.colors[2]}
                d="M24 0H0v24h24V0z"
            />
            <path
                strokeLinejoin="round"
                strokeLinecap="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="m12 2 2.627 1.916 3.25-.006 1 3.094L21.51 8.91 20.5 12l1.01 3.09-2.633 1.906-1 3.094-3.25-.006L12 22l-2.627-1.916-3.25.006-1-3.094L2.49 15.09 3.5 12 2.49 8.91l2.633-1.906 1-3.094 3.25.006L12 2z"
            />
            <path
                strokeLinejoin="round"
                strokeLinecap="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="m8.5 12 2.5 2.5 5-5"
            />
        </svg>
    )
);
