// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable max-len, import/no-default-export */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'
export default IconWrapper('tool', true, (props: ISvgIconProps) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path fillOpacity=".01" fill="#fff" d="M24 0H0v24h24V0z" />
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke="#3E3E3E"
      d="M22 8a6 6 0 0 1-8.805 5.305L4.5 22 2 19.5l8.695-8.695a6 6 0 0 1 8.11-8.11L15 6.5 17.5 9l3.805-3.805C21.75 6.032 22 6.987 22 8z"
    />
  </svg>
))
