// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template */

/**
 * @file Twitter platform/twitter.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import {ISvgIconProps, IconWrapper} from '../icon';

export default IconWrapper(
    'twitter',
    false,
    (props: ISvgIconProps) => (
        <svg
            fill="none"
            viewBox="0 0 24 24"
        >
            <path
                fillOpacity=".01"
                fill={props.colors[2]}
                d="M24 0H0v24h24V0z"
            />
            <path
                strokeLinejoin="round"
                strokeWidth="2"
                stroke={props.colors[0]}
                d="M2.5 17.881c.964.533 7.946 4.558 12.91 1.456s4.69-8.445 4.69-10.894c.45-.942 1.4-1.421 1.4-3.971-.933.862-1.86 1.155-2.782.88-.904-1.377-2.146-1.986-3.728-1.827-2.373.238-3.242 2.566-2.986 5.578-3.659 1.85-6.528-1.341-8.007-3.751-.494 1.898-.97 4.177 0 6.698.647 1.68 2.202 3.101 4.666 4.262-2.497 1.353-4.551 1.876-6.163 1.57z"
            />
        </svg>
    )
);
