// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file User basic/user.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('user', false, (props: ISvgIconProps) => (
  <svg fill="none" viewBox="0 0 24 24">
    <path
      strokeLinejoin="round"
      strokeLinecap="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="M12 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM21 22a9 9 0 1 0-18 0"
    />
  </svg>
))
