// Auto Generated by @brickdoc/design-icons, don't change it manually.
/* eslint-disable import/no-default-export, prefer-template, @typescript-eslint/no-unused-vars */

/**
 * @file Windows platform/windows.svg
 * @author Auto Generated by Brickdoc
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react'
import { ISvgIconProps, IconWrapper } from '../icon'

export default IconWrapper('windows', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 24 24" fill="none">
    <path fillOpacity=".01" fill={props.colors[2]} d="M24 0H0v24h24V0z" />
    <path
      strokeLinejoin="round"
      strokeWidth="2"
      stroke={props.colors[0]}
      d="m3.375 5.531 6.469-.862v6.037H3.375V5.531zm9.056-1.109 8.194-1.047v7.331h-8.194V4.422zm0 9.303 8.194.192v6.708l-8.194-1.342v-5.558zm-9.056-.431 6.469.155V18.9l-6.469-1.09v-4.516z"
    />
  </svg>
))
