# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grpc/main.proto for package 'anti_corruption'

require 'grpc'
require 'grpc/main_pb'

module AntiCorruption
  module MetadataService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'anti_corruption.MetadataService'

      rpc :GetMetadata, ::Google::Protobuf::Empty, ::AntiCorruption::Metadata
    end

    Stub = Service.rpc_stub_class
  end
end
