import React, { CSSProperties } from 'react'
import cx from 'classnames'

export interface IconProps {
  // copy from Icon Park type definitions
  // TODO: generate correct type definitions automatically
  name:
    | 'rte-h3'
    | 'list-unordered'
    | 'list-ordered'
    | 'text-underline'
    | 'strikethrough'
    | 'bold-words'
    | 'rte-h2'
    | 'rte-h1'
    | 'italics'
    | 'font-size'
    | 'line-down'
    | 'add'
    | 'alarm'
    | 'android'
    | 'apple'
    | 'api'
    | 'app-store'
    | 'attention'
    | 'browser'
    | 'bug'
    | 'certificate'
    | 'calendar'
    | 'clear'
    | 'close-one'
    | 'close'
    | 'close-one-fill'
    | 'check-one'
    | 'check-one-fill'
    | 'check'
    | 'config'
    | 'color-card'
    | 'copy'
    | 'arrow-left'
    | 'arrow-down'
    | 'arrow-circle-up'
    | 'arrow-circle-right'
    | 'arrow-circle-down'
    | 'arrow-right'
    | 'arrow-up'
    | 'arrow-circle-left'
    | 'double-down'
    | 'double-right'
    | 'double-left'
    | 'double-up'
    | 'up'
    | 'down'
    | 'right'
    | 'left'
    | 'corner-down-left'
    | 'corner-down-right'
    | 'upload'
    | 'download'
    | 'edit'
    | 'experiment'
    | 'facebook'
    | 'filter'
    | 'folder-close'
    | 'folder-open'
    | 'google'
    | 'github'
    | 'hamburger-button'
    | 'help'
    | 'info'
    | 'pic'
    | 'notes'
    | 'plus'
    | 'zoom-in'
    | 'add-241aeojl'
    | 'reduce'
    | 'minus'
    | 'zoom-out'
    | 'search'
    | 'success'
    | 'preview-close'
    | 'preview-open'
    | 'protect'
    | 'instagram'
    | 'lark'
    | 'international'
    | 'inbox'
    | 'link'
    | 'lightning'
    | 'lock'
    | 'mail'
    | 'message'
    | 'menu-fold'
    | 'menu-unfold'
    | 'page'
    | 'arrow-right-small'
    | 'oval-love'
    | 'report'
    | 'save'
    | 'rss'
    | 'rotation'
    | 'setting'
    | 'setting-config'
    | 'shield'
    | 'sort'
    | 'sort-242ci1f6'
    | 'tag'
    | 'time'
    | 'star'
    | 'to-top'
    | 'to-bottom'
    | 'user'
    | 'twitter'
    | 'tencent-qq'
    | 'tiktok'
    | 'weibo'
    | 'windows'
    | 'wechat'
    | 'friends-circle'
    | 'alipay'
    | 'tool'
    | 'tips'
    | 'high-light'
    | 'formula'
    | 'alphabetical-sorting1'
    | 'point'
    | 'platte'
    | 'dividing-line'
    | 'alphabetical-sorting2'
    | 'drag'
    | 'merge-cells'
    | 'add-text'
    | 'bring-forward'
    | 'code'
    | 'paragraph-break'
    | 'quote'
    | 'font-size-242hge72'
    | 'row-height'
    | 'text-style'
    | 'text'
    | 'textarea'
    | 'image'
    | 'file-image'
    | 'more'
    | 'file-pdf'
    | 'face'
    | 'redo'
  className?: string
  style?: CSSProperties
}

export const Icon: React.FC<IconProps> = ({ name, className, style }) => {
  return (
    <span className={cx('brk-icon', className)} style={style}>
      <iconpark-icon name={name} />
    </span>
  )
}
